import { defineTable } from "convex/server";
import { v } from "convex/values";
import { visibility, communityState, lessonMeta } from "./learnModel";
export const collectionItem = v.union(v.object({ kind: v.literal("lesson"), id: v.id("lessons"), versionId: v.id("lessonVersions") }), v.object({ kind: v.literal("source"), id: v.id("learnSources") }));
export const courseModule = v.object({ id: v.string(), title: v.string(), lessonIds: v.array(v.id("lessons")), assessments: v.array(v.object({ kind: v.union(v.literal("form"), v.literal("quiz")), id: v.string() })) });
export const courseDetails = v.object({ outcomes: v.array(v.string()), level: v.union(v.literal("all"), v.literal("beginner"), v.literal("intermediate"), v.literal("advanced")), estimatedMinutes: v.optional(v.number()) });
export const cards = v.array(v.object({ id: v.string(), front: v.string(), back: v.string(), conceptIds: v.array(v.string()) }));
export const assetTables = {
  courseLessonMemberships: defineTable({ courseId: v.id("learnCollections"), lessonId: v.id("lessons"), ownerId: v.string() }).index("by_courseId", ["courseId"]).index("by_ownerId_and_lessonId", ["ownerId", "lessonId"]),
  courseMembershipState: defineTable({ key: v.literal("v1"), complete: v.boolean(), generation: v.number(), cursor: v.optional(v.union(v.string(), v.null())) }).index("by_key", ["key"]),
  learnCollections: defineTable({ searchText: v.optional(v.string()), ownerId: v.string(), metadata: lessonMeta, modules: v.optional(v.array(courseModule)), details: v.optional(courseDetails), items: v.array(collectionItem), /** Course outline: the draft lesson order (courses.ts). items holds the published snapshot. */ lessonIds: v.optional(v.array(v.id("lessons"))), archived: v.optional(v.boolean()), revision: v.number(), visibility, audienceTeamId: v.optional(v.id("businessTeams")), communityState, publishedVersionId: v.optional(v.id("collectionVersions")), createdAt: v.number(), updatedAt: v.number() }).index("by_ownerId_and_updatedAt", ["ownerId", "updatedAt"]).index("by_ownerId_and_archived_and_updatedAt", ["ownerId", "archived", "updatedAt"]).index("by_visibility_and_updatedAt", ["visibility", "updatedAt"]).searchIndex("search_public", { searchField: "searchText", filterFields: ["visibility", "communityState"] }),
  collectionVersions: defineTable({ collectionId: v.id("learnCollections"), number: v.number(), metadata: lessonMeta, modules: v.optional(v.array(courseModule)), details: v.optional(courseDetails), items: v.array(collectionItem), publishedAt: v.number() }).index("by_collectionId_and_number", ["collectionId", "number"]),
  lessonAssessments: defineTable({ lessonId: v.id("lessons"), asset: v.union(v.object({ kind: v.literal("form"), id: v.id("forms") }), v.object({ kind: v.literal("quiz"), id: v.id("quizzes") })), label: v.string(), order: v.number() }).index("by_lessonId_and_asset", ["lessonId", "asset"]).index("by_lessonId_and_order", ["lessonId", "order"]),
  flashcardSets: defineTable({ archived: v.optional(v.boolean()), ownerId: v.string(), title: v.string(), cards, revision: v.number(), visibility, audienceTeamId: v.optional(v.id("businessTeams")), publishedVersionId: v.optional(v.id("flashcardVersions")), parentSetId: v.optional(v.id("flashcardSets")), parentVersionId: v.optional(v.id("flashcardVersions")), originSetId: v.optional(v.id("flashcardSets")), updatedAt: v.number() }).index("by_ownerId_and_updatedAt", ["ownerId", "updatedAt"]).index("by_ownerId_and_archived_and_updatedAt", ["ownerId", "archived", "updatedAt"]).index("by_visibility_and_updatedAt", ["visibility", "updatedAt"]),
  lessonFlashcards: defineTable({ lessonId: v.id("lessons"), setId: v.id("flashcardSets"), versionId: v.id("flashcardVersions"), label: v.string(), order: v.number() }).index("by_lessonId_and_setId", ["lessonId", "setId"]).index("by_lessonId_and_order", ["lessonId", "order"]),
  flashcardStudyState: defineTable({ userKey: v.string(), versionId: v.id("flashcardVersions"), cardId: v.string(), revision: v.number(), reviews: v.number(), lapses: v.number(), box: v.number(), dueAt: v.number(), lastReviewedAt: v.number() }).index("by_userKey_and_versionId_and_cardId", ["userKey", "versionId", "cardId"]),
  flashcardStudyEvidence: defineTable({ userKey: v.string(), eventId: v.string(), versionId: v.id("flashcardVersions"), cardId: v.string(), rating: v.union(v.literal("again"), v.literal("hard"), v.literal("good"), v.literal("easy")), reviewedAt: v.number(), resultingRevision: v.number(), dueAt: v.number(), box: v.number() }).index("by_userKey_and_eventId", ["userKey", "eventId"]).index("by_userKey_and_versionId_and_reviewedAt", ["userKey", "versionId", "reviewedAt"]),
  flashcardVersions: defineTable({ setId: v.id("flashcardSets"), number: v.number(), title: v.string(), cards, publishedAt: v.number() }).index("by_setId_and_number", ["setId", "number"]),
};
