import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";

export const ADMIN_PLATFORM_TOOLS = ["get_admin_overview", "refresh_admin_analytics", "list_admin_users", "list_admin_content", "list_admin_learning_content", "list_admin_teams", "list_admin_activity", "moderate_admin_user", "moderate_admin_content"] as const;
export const ADMIN_CRM_TOOLS = ["get_crm_activity", "set_crm_contact_stages", "complete_crm_follow_up"] as const;

export function registerAdminTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
  const ref = z.string().min(1).max(100);
  const page = z.object({ numItems: z.number().int().min(1).max(48), cursor: z.string().max(4096).nullable() }).strict();
  const read = { readOnlyHint: true, destructiveHint: false, openWorldHint: false, idempotentHint: true };
  const write = { ...read, readOnlyHint: false };
  const ok = { ok: z.boolean() };
  const pageOutput = { page: z.array(z.record(z.string(), z.unknown())), isDone: z.boolean(), continueCursor: z.string(), splitCursor: z.string().nullable().optional(), pageStatus: z.enum(["SplitRecommended", "SplitRequired"]).nullable().optional() };
  const _meta = { securitySchemes };
  server.registerTool("get_admin_overview", { title: "Read platform overview (admin)", description: "Administrators only: read the same aggregate platform metrics, running state and completion date shown in the administration overview. overview is null before the first refresh. Does not return individual responses.", inputSchema: {}, outputSchema: { overview: z.record(z.string(), z.unknown()).nullable() }, annotations: read, _meta }, input => run("get_admin_overview", input, () => "Platform overview loaded."));
  server.registerTool("refresh_admin_analytics", { title: "Refresh platform overview (admin)", description: "Administrators only: start the same asynchronous bounded platform metrics refresh as the admin UI. Read get_admin_overview afterwards to check running/completedAt. An existing recent refresh is reused.", inputSchema: {}, outputSchema: ok, annotations: write, _meta }, input => run("refresh_admin_analytics", input, () => "Platform refresh requested."));
  server.registerTool("list_admin_users", { title: "List platform accounts (admin)", description: "Administrators only: page through platform accounts including email, account state, suspension and moderation reason. Optional email searches the exact indexed email. Contains private account metadata; retrieve only requested accounts. Follow continueCursor until isDone.", inputSchema: { paginationOpts: page, email: z.string().max(254).optional(), search: z.string().max(200).optional().describe("Name, email or username words; returns the best matches in one page.") }, outputSchema: pageOutput, annotations: read, _meta }, input => run("list_admin_users", input, () => "Platform accounts loaded."));
  server.registerTool("list_admin_content", { title: "List platform forms and quizzes (admin)", description: "Administrators only: page the same forms inventory (quizzes are quiz forms) as the admin UI, including status, owner, holds and response counts. Returns metadata only, never question content, answer keys or respondent answers.", inputSchema: { kind: z.enum(["forms"]), paginationOpts: page, search: z.string().max(200).optional().describe("Title words or an exact id; returns the best matches in one page.") }, outputSchema: pageOutput, annotations: read, _meta }, input => run("list_admin_content", input, () => "Platform content loaded."));
  server.registerTool("list_admin_learning_content", { title: "List platform learning content (admin)", description: "Administrators only: page courses, lessons or flashcard sets, including draft/live/archived status, title, owner name/email, dates and lesson/card count (lessons count is zero). Returns metadata only; no private lesson blocks or card answers.", inputSchema: { kind: z.enum(["courses", "lessons", "flashcards"]), paginationOpts: page }, outputSchema: pageOutput, annotations: read, _meta }, input => run("list_admin_learning_content", input, () => "Platform learning content loaded."));
  server.registerTool("list_admin_teams", { title: "List platform Business teams (admin)", description: "Administrators only: page Business team names, owner name/email, creation dates, member counts and shared resource counts. Does not return invitations, member identities or private shared content.", inputSchema: { paginationOpts: page }, outputSchema: pageOutput, annotations: read, _meta }, input => run("list_admin_teams", input, () => "Platform teams loaded."));
  server.registerTool("list_admin_activity", { title: "Read administration activity (admin)", description: "Administrators only: read the latest 50 audit events shown in the admin UI, with actor, target, action, reason and date.", inputSchema: {}, outputSchema: { activity: z.array(z.record(z.string(), z.unknown())) }, annotations: read, _meta }, input => run("list_admin_activity", input, () => "Administration activity loaded."));
  server.registerTool("moderate_admin_user", { title: "Moderate platform account (admin)", description: "Administrators only, on explicit request: activate, suspend or ban an account from list_admin_users. accountId is its users-table _id. A reason is required; suspension days default to 7 and must be 1–365. The same self-restriction guard, expiry scheduling and audit log as the UI apply. Changes account access immediately; do not retry after uncertain success.", inputSchema: { accountId: ref, state: z.enum(["active", "suspended", "banned"]), days: z.number().int().min(1).max(365).optional(), reason: z.string().trim().min(1).max(500) }, outputSchema: ok, annotations: { ...write, destructiveHint: true, idempotentHint: false }, _meta }, input => run("moderate_admin_user", input, () => "Account moderation updated."));
  server.registerTool("moderate_admin_content", { title: "Hold or release platform content (admin)", description: "Administrators only, on explicit request: hold or release a form ID from list_admin_content. A reason is required. Holding removes public access through the same UI moderation logic and writes an audit event; releasing a hold does not republish a closed form.", inputSchema: { targetId: ref, hold: z.boolean(), reason: z.string().trim().min(1).max(500) }, outputSchema: ok, annotations: { ...write, destructiveHint: true }, _meta }, input => run("moderate_admin_content", input, () => "Content hold updated."));
  server.registerTool("get_crm_activity", { title: "Read CRM contact activity (admin)", description: "Administrators only: read the latest 100 audit events for an existing contact ID returned by list_crm_contacts or get_crm_contact. Includes actor, reason and date. Does not send messages.", inputSchema: { contactId: ref }, outputSchema: { activity: z.array(z.record(z.string(), z.unknown())) }, annotations: read, _meta }, input => run("get_crm_activity", input, () => "CRM activity loaded."));
  server.registerTool("set_crm_contact_stages", { title: "Change CRM contact stages (admin)", description: "Administrators only, on explicit request: set one stage for 1–48 selected CRM contacts. Supports the same batch stage change as the table/pipeline UI, preserves other fields, and audits each changed contact. Never sends messages.", inputSchema: { contactIds: z.array(ref).min(1).max(48), stage: z.enum(["new", "contacted", "active", "closed"]) }, outputSchema: ok, annotations: write, _meta }, input => run("set_crm_contact_stages", input, () => "CRM stages updated."));
  server.registerTool("complete_crm_follow_up", { title: "Complete CRM follow-up (admin)", description: "Administrators only, on explicit request: clear a contact's scheduled follow-up through the same UI action and audit it. Already completed follow-ups are unchanged. Does not send email or notifications.", inputSchema: { contactId: ref }, outputSchema: ok, annotations: write, _meta }, input => run("complete_crm_follow_up", input, () => "CRM follow-up completed."));
}
