import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
const ref = z.string().min(1).max(100);
const edit = { formId: ref, expectedRevision: z.number().int().min(1) };
const rule = z.object({ match: z.enum(["all", "any"]), conditions: z.array(z.object({ fieldId: ref, op: z.enum(["equals", "not_equals", "includes", "not_includes", "answered", "not_answered", "gt", "gte", "lt", "lte"]), value: z.union([z.string(), z.number()]).optional() }).strict()).max(20) }).strict();
export function registerTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
  const common = { outputSchema: { revision: z.number().int() }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false }, _meta: { securitySchemes } };
  server.registerTool("set_form_branching", { ...common, description: "Explicitly replace or clear one field/ending visibility rule. Requires editor access and current draft revision. Other fields and published versions remain unchanged. Reload after uncertain success before retrying.", inputSchema: { ...edit, target: z.enum(["field", "ending"]), targetId: ref, rule: rule.nullable() } }, input => run("set_form_branching", input, () => "Draft branching updated."));
  server.registerTool("upsert_form_file_question", { ...common, description: "Create or update a file question in a normal form draft. Existing question order and branching are preserved; other question types cannot be replaced. Files follow Chaos upload authorization and platform limits. Requires current revision; never publishes.", inputSchema: { ...edit, fieldId: ref, label: z.string().min(1).max(500), required: z.boolean(), maxFiles: z.number().int().min(1).max(5), description: z.string().max(2000).optional(), beforeFieldId: ref.optional() } }, input => run("upsert_form_file_question", input, () => "Draft file question updated."));
  const controlPatch = z.object({ access: z.enum(["public", "signed_in", "code"]).optional(), opensAt: z.number().finite().nullable().optional(), closesAt: z.number().finite().nullable().optional(), responseLimit: z.number().int().positive().nullable().optional(), retentionDays: z.number().int().min(1).max(3650).nullable().optional(), onePerPerson: z.boolean().optional(), allowEditAfterSubmit: z.boolean().optional(), allowEditAfterClose: z.boolean().optional(), collectPartial: z.boolean().optional(), allowResumeLink: z.boolean().optional(), hideBranding: z.boolean().optional(), hiddenFields: z.array(z.string()).max(20).optional(), allowedEmails: z.array(z.string()).max(100).optional(), allowedDomains: z.array(z.string()).max(100).optional() }).strict();
  server.registerTool("get_form_response_controls", { description: "Read owned form response controls and their independent settings revision. Returns no access-code hash or plaintext code, respondent data or answer keys.", inputSchema: { formId: ref }, outputSchema: { settings: z.record(z.string(), z.unknown()), settingsRevision: z.number(), hasAccessCode: z.boolean() }, annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false, idempotentHint: true }, _meta: { securitySchemes } }, input => run("get_form_response_controls", input, () => "Response controls loaded."));
  server.registerTool("set_form_response_controls", { description: "Explicit owner-only revision-protected response configuration: access, dates, limits, one-per-person, retention, editing, hidden fields and verified email/domain rules. Omitted values stay unchanged; null clears dates/caps/retention. Access changes can affect existing public links. Retention can schedule data deletion. Pro branding entitlement is enforced by shared server policy.", inputSchema: { formId: ref, expectedSettingsRevision: z.number().int().nonnegative(), patch: controlPatch, accessCode: z.string().max(100).optional() }, outputSchema: { settingsRevision: z.number() }, annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: true, idempotentHint: false }, _meta: { securitySchemes } }, input => run("set_form_response_controls", input, () => "Response controls updated."));

}
