import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
const id = z.string().min(1).max(100);
const asset = z.discriminatedUnion("kind", [z.object({ kind: z.literal("form"), id }), z.object({ kind: z.literal("quiz"), id })]);
export function registerAssessmentTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
  const _meta = { securitySchemes }, read = { readOnlyHint: true, destructiveHint: false, openWorldHint: false, idempotentHint: true }, write = { ...read, readOnlyHint: false };
  server.registerTool("attach_lesson_quiz", { description: "Attach an owned existing quiz to an owned lesson by stable identity. Quizzes made with create_form or create_game_draft are forms: pass asset {kind:\"form\", id} with the id those tools returned; kind \"quiz\" is only for classic quizzes. Updates label/order idempotently; creates no quiz copy and never publishes.", inputSchema: { lessonId: id, asset, label: z.string().trim().min(1).max(200), order: z.number().int().min(0).max(1000) }, outputSchema: { relationshipId: id }, annotations: write, _meta }, input => run("attach_lesson_quiz", input, () => "Assessment attached."));
  server.registerTool("get_lesson_quizzes", { description: "List bounded assessment references linked to a permitted lesson. Quiz content and answer keys retain independent access checks; references never grant access.", inputSchema: { lessonId: id }, outputSchema: { assessments: z.array(z.record(z.string(), z.unknown())).max(50) }, annotations: read, _meta }, input => run("get_lesson_quizzes", input, () => "Assessment references loaded."));
  server.registerTool("create_lesson_live_game", { description: "Create an existing Chaos Live game from an owned assessment linked to an owned lesson. Reuses normal publication, eligibility, rate and plan rules. Call only for explicit intent to prepare Live; each success creates a room and is not safe to retry blindly.", inputSchema: { lessonId: id, asset }, outputSchema: { gameId: id }, annotations: { ...write, openWorldHint: true, idempotentHint: false }, _meta }, input => run("create_lesson_live_game", input, () => "Live room created."));
}
