import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
const ref = z.string().min(1).max(100);
const course = { courseId: ref };
const visibility = z.enum(["public", "restricted", "private"]);
const read = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
const write = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
export function registerCourseTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
 const meta = { securitySchemes };
 server.registerTool("create_course", { description: "Create an owned course draft. Never publishes. Each call creates a new course; inspect the library before retrying uncertain success.", inputSchema: { title: z.string().trim().min(1).max(200).optional(), language: z.string().min(1).max(35).optional() }, outputSchema: { courseId: ref }, annotations: write, _meta: meta }, input => run("create_course", input, () => "Course draft created."));
 server.registerTool("get_course", { description: "Read the current owner's course builder metadata and ordered lesson summaries. No lesson content or respondent data. Use get_lesson for lesson drafts.", inputSchema: course, outputSchema: { id: ref, title: z.string(), description: z.string(), coverUrl: z.string().optional(), language: z.string(), tags: z.array(z.string()), visibility, published: z.boolean(), publishedAt: z.number().nullable(), canPrivate: z.boolean(), lessons: z.array(z.object({ id: ref, title: z.string(), description: z.string(), published: z.boolean(), changed: z.boolean(), blocks: z.number() })), revision: z.number() }, annotations: read, _meta: meta }, input => run("get_course", input, () => "Course loaded."));
 server.registerTool("update_course", { description: "Edit owned course draft metadata without publishing. Omitted fields stay unchanged; null coverUrl removes the cover. Published metadata changes only on explicit publish_course.", inputSchema: { ...course, title: z.string().trim().min(1).max(200).optional(), description: z.string().max(4000).optional(), coverUrl: z.string().url().max(2008).nullable().optional(), language: z.string().min(1).max(35).optional(), tags: z.array(z.string().max(40)).max(12).optional() }, outputSchema: { ok: z.boolean() }, annotations: { ...write, idempotentHint: true }, _meta: meta }, input => run("update_course", input, () => "Course draft updated."));
 server.registerTool("set_course_outline", { description: "Replace the complete ordered course draft outline with up to 100 owned lesson IDs. Get the course first and preserve all wanted lessons. Removing an ID does not delete the lesson. Does not publish.", inputSchema: { ...course, lessonIds: z.array(ref).max(100) }, outputSchema: { ok: z.boolean() }, annotations: { ...write, destructiveHint: true, idempotentHint: true }, _meta: meta }, input => run("set_course_outline", input, () => "Course draft outline updated."));
 server.registerTool("add_course_lesson", { description: "Create a blank owned lesson draft at the end of an owned course (maximum 100 lessons). Edit with existing lesson tools. Does not publish. Do not automatically retry uncertain success.", inputSchema: { ...course, title: z.string().trim().min(1).max(200).optional() }, outputSchema: { lessonId: ref }, annotations: write, _meta: meta }, input => run("add_course_lesson", input, () => "Lesson draft added."));
 server.registerTool("publish_course", { description: "Publish an owned course AND its outlined lessons with requested visibility, including draft changes. Only on explicit user request after review. Private visibility requires Business. Inspect per-lesson problems when ok is false; some lessons may have published. Repeated success creates another snapshot; do not automatically retry.", inputSchema: { ...course, visibility }, outputSchema: { ok: z.boolean(), problems: z.array(z.object({ lessonId: ref, title: z.string(), message: z.string() })).optional() }, annotations: { ...write, destructiveHint: true, openWorldHint: true }, _meta: meta }, input => run("publish_course", input, data => data.ok ? "Course published." : "Course publication needs review."));
}
