import { lessonDocumentSchema, lessonMetadataSchema } from "./learn";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import type { McpFlow } from "./flow";
const ref = z.string().min(1).max(100);
const course = { courseId: ref };
const visibility = z.enum(["public", "restricted", "private"]);
const read = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
const write = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
export function registerCourseTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[], { call, flow }: McpFlow) {
 const meta = { securitySchemes };
 server.registerTool("get_my_card", { description: "Read your own real Chaos Card: name, username, avatar seed, join date and style. No private responses.", inputSchema: {}, annotations: read, _meta: meta }, input => run("get_my_card", input, () => "Your Chaos Card loaded."));
 server.registerTool("customize_my_card", { description: "Customize your own Chaos Card. Choose name, reserved username, style 0–31, generated avatar 0–7. Existing public URL aliases remain valid. Only explicit finishOnboarding or skip marks first-account setup complete; edits are optional and can be changed later.", inputSchema: { name: z.string().trim().min(1).max(100).optional(), username: ref.optional(), style: z.number().int().min(0).max(31).optional(), avatar: z.number().int().min(0).max(7).optional(), finishOnboarding: z.boolean().optional(), skip: z.boolean().optional() }, annotations: write, _meta: meta }, input => run("customize_my_card", input, () => "Your Chaos Card updated."));
 server.registerTool("list_my_students", { description: "Read your private Students roster with cursor pagination. Includes account cards and guest labels/context, never answers or scores. Anonymous participation stays anonymous; public relationships require student opt-in.", inputSchema: { cursor: z.string().optional(), limit: z.number().int().min(1).max(48).optional() }, annotations: read, _meta: meta }, input => run("list_my_students", input, () => "Private student roster loaded."));
 server.registerTool("set_student_card_visibility", { description: "Choose whether YOUR real Card appears publicly on an existing teacher's Students section. Default is private. Cannot expose another person's relationship or create a new one.", inputSchema: { username: ref, visible: z.boolean() }, annotations: write, _meta: meta }, input => run("set_student_card_visibility", input, () => "Your student Card visibility updated."));
 const cover = z.union([z.string().url().max(2008), z.string().regex(/^\/covers\/[a-z0-9/_-]+\.(jpg|svg)$/)]);
 const icon = z.string().min(1).max(16);
 server.registerTool("create_full_course", {
  description: "Create a whole course in one call: title, description, cover (https link or /covers/ gallery path), cover position, icon, and up to 100 lessons in order, each with its own blocks, cover and icon. Creates drafts by default. Only explicit publish: true publishes each lesson and then the course. Private needs Business. If something fails part-way, the result says what was created so you can continue with the course tools instead of starting again.",
  inputSchema: {
   title: z.string().trim().min(1).max(200), description: z.string().max(4000).optional(), language: z.string().min(1).max(35).optional(), tags: z.array(z.string().max(40)).max(12).optional(),
   coverUrl: cover.optional(), coverY: z.number().min(0).max(100).optional(), icon: icon.optional(),
   lessons: z.array(z.object({ title: z.string().trim().min(1).max(200), description: z.string().max(4000).optional(), coverUrl: cover.optional(), icon: icon.optional(), document: lessonDocumentSchema })).min(1).max(100),
   publish: z.boolean().optional(), visibility: visibility.optional(),
  },
  outputSchema: { courseId: ref, lessonIds: z.array(ref), published: z.boolean(), problems: z.array(z.object({ lessonId: ref, title: z.string(), message: z.string() })).optional() },
  annotations: { ...write, openWorldHint: true },
  _meta: meta,
 }, ({ title, description, language, tags, coverUrl, coverY, icon: courseIcon, lessons, publish, visibility: chosen }) => flow(async () => {
  const { courseId } = await call("create_course", { title, ...(language ? { language } : {}) });
  const lessonIds: string[] = [];
  try {
   await call("update_course", { courseId, ...(description !== undefined ? { description } : {}), ...(tags ? { tags } : {}), ...(coverUrl ? { coverUrl } : {}), ...(coverY !== undefined ? { coverY } : {}), ...(courseIcon ? { icon: courseIcon } : {}) });
   for (const lesson of lessons) {
    const { lessonId } = await call("add_course_lesson", { courseId, title: lesson.title });
    lessonIds.push(lessonId as string);
    // A new lesson starts at revision 0 (convex/lessons.ts createLessonForActor).
    await call("save_lesson_draft", { lessonId, expectedRevision: 0, document: lesson.document, metadata: { title: lesson.title, description: lesson.description ?? "", language: language ?? "en", tags: [], indexing: "index", ...(lesson.coverUrl ? { coverUrl: lesson.coverUrl } : {}), ...(lesson.icon ? { icon: lesson.icon } : {}) } });
   }
  } catch (error) {
   const message = error instanceof Error ? error.message : String(error);
   throw new Error(`${message} (course ${courseId} was created with ${lessonIds.length} of ${lessons.length} lessons; continue with get_course and the lesson tools)`);
  }
  if (publish !== true) return { text: `Course draft created with ${lessonIds.length} lessons.`, data: { courseId, lessonIds, published: false } };
  for (const lessonId of lessonIds) {
   const lesson = await call("get_lesson", { lessonId });
   const result = await call("publish_lesson", { lessonId, expectedRevision: lesson.revision, visibility: chosen ?? "public" });
   if (!result.ok) return { text: "Course draft created; publish blocked by a lesson. Review before continuing.", data: { courseId, lessonIds, published: false } };
  }
  const p = await call("publish_course", { courseId, visibility: chosen ?? "public" });
  return p.ok ? { text: `Course published with ${lessonIds.length} lessons.`, data: { courseId, lessonIds, published: true } }
   : { text: "Course created; some lessons need fixes before it can publish.", data: { courseId, lessonIds, published: false, problems: p.problems } };
 }));
 server.registerTool("create_course", { description: "Create an empty owned course draft to build step by step (create_full_course does everything in one call). Never publishes. Each call creates a new course; inspect the library before retrying uncertain success.", inputSchema: { title: z.string().trim().min(1).max(200).optional(), language: z.string().min(1).max(35).optional() }, outputSchema: { courseId: ref }, annotations: write, _meta: meta }, input => run("create_course", input, () => "Course draft created."));
 const details = z.object({ outcomes: z.array(z.string().trim().min(1).max(500)).max(20), level: z.enum(["all", "beginner", "intermediate", "advanced"]), estimatedMinutes: z.number().int().min(1).max(10000).optional() });
 const module = z.object({ id: z.string().regex(/^[a-zA-Z0-9_-]{1,100}$/), title: z.string().trim().min(1).max(200), lessonIds: z.array(ref).max(100), assessments: z.array(z.object({ kind: z.enum(["form", "quiz"]), id: ref })).max(20) });
 server.registerTool("set_course_modules", { description: "Replace optional course draft modules without publishing. Read get_course first; preserve wanted modules and assignments. Each outlined lesson belongs to at most one module. Modules reference reusable owned quiz assets, not copies. Empty modules removes grouping, keeping lessons.", inputSchema: { ...course, modules: z.array(module).max(30) }, outputSchema: { ok: z.boolean() }, annotations: { ...write, destructiveHint: true, idempotentHint: true }, _meta: meta }, input => run("set_course_modules", input, () => "Course modules updated."));
 server.registerTool("export_course_manifest", { description: "Read the owner-only versioned course archive manifest with metadata, outcomes, modules and ordered lesson IDs. Use existing lesson/deck/quiz reads to transfer structured content. No student responses, progress or file bytes. Builder Export course.zip includes owned binary files.", inputSchema: course, outputSchema: { manifest: z.object({ format: z.literal("chaos-course"), version: z.literal(1), metadata: lessonMetadataSchema, details: details.optional(), modules: z.array(module), lessonIds: z.array(ref) }) }, annotations: read, _meta: meta }, input => run("export_course_manifest", input, () => "Course export manifest loaded."));
 server.registerTool("import_course_lesson", { description: "Import one validated lesson into an owned course as a private draft, appending it to the outline. Remap all quiz/deck/source IDs to existing owned imported assets first. Never publishes or imports student evidence. Maximum 100 lessons per course. Do not retry uncertain success.", inputSchema: { ...course, metadata: lessonMetadataSchema, document: lessonDocumentSchema }, outputSchema: { lessonId: ref }, annotations: write, _meta: meta }, input => run("import_course_lesson", input, () => "Private lesson imported."));
 server.registerTool("get_course_lesson", { description: "Read a lesson from a readable course publication, preserving the exact immutable version in that course. Current asset restrictions still apply. Returns no response data.", inputSchema: { ...course, lessonId: ref }, outputSchema: { lesson: z.object({ lessonId: ref, versionId: ref, title: z.string(), document: lessonDocumentSchema }).nullable() }, annotations: read, _meta: meta }, input => run("get_course_lesson", input, () => "Course lesson loaded."));
 server.registerTool("remember_course", { description: "Add a readable published course to your private learning dashboard and update its recent activity. Does not publish or enroll other people.", inputSchema: course, outputSchema: { ok: z.boolean() }, annotations: { ...write, idempotentHint: true }, _meta: meta }, input => run("remember_course", input, () => "Course added to your learning dashboard."));
 server.registerTool("get_course_progress", { description: "Read only your own lesson progress in a readable course's published versions. Does not disclose other students or response data.", inputSchema: course, outputSchema: { lessons: z.array(z.object({ lessonId: ref, completed: z.boolean(), percent: z.number() })) }, annotations: read, _meta: meta }, input => run("get_course_progress", input, () => "Your course progress loaded."));
 server.registerTool("get_course", { description: "Read the current owner's course builder metadata and ordered lesson summaries. No lesson content or respondent data. Use get_lesson for lesson drafts.", inputSchema: course, outputSchema: { id: ref, title: z.string(), description: z.string(), coverUrl: z.string().optional(), coverY: z.number().optional(), icon: z.string().optional(), language: z.string(), tags: z.array(z.string()), visibility, published: z.boolean(), publishedAt: z.number().nullable(), canPrivate: z.boolean(), modules: z.array(module), details: details.optional(), lessons: z.array(z.object({ id: ref, title: z.string(), description: z.string(), published: z.boolean(), changed: z.boolean(), blocks: z.number() })), revision: z.number() }, annotations: read, _meta: meta }, input => run("get_course", input, () => "Course loaded."));
 server.registerTool("update_course", { description: "Edit owned course draft metadata without publishing. Omitted fields stay unchanged; null coverUrl removes the cover. coverUrl is an https image link or a /covers/ gallery path (same gallery as lessons); coverY (0-100) is the cover's vertical focus; icon is a Lucide icon name (e.g. BookOpen, Brain, Sparkles) or emoji shown above the title. Optional details sets learning outcomes, level and estimated duration. Published metadata changes only on explicit publish_course.", inputSchema: { ...course, title: z.string().trim().min(1).max(200).optional(), description: z.string().max(4000).optional(), coverUrl: z.union([z.string().url().max(2008), z.string().regex(/^\/covers\/[a-z0-9/_-]+\.(jpg|svg)$/)]).nullable().optional(), coverY: z.number().min(0).max(100).nullable().optional(), icon: z.string().min(1).max(16).nullable().optional(), language: z.string().min(1).max(35).optional(), tags: z.array(z.string().max(40)).max(12).optional(), details: details.optional() }, outputSchema: { ok: z.boolean() }, annotations: { ...write, idempotentHint: true }, _meta: meta }, input => run("update_course", input, () => "Course draft updated."));
 server.registerTool("set_course_outline", { description: "Replace the complete ordered course draft outline with up to 100 owned lesson IDs. Get the course first and preserve all wanted lessons. Removing an ID does not delete the lesson. Does not publish.", inputSchema: { ...course, lessonIds: z.array(ref).max(100) }, outputSchema: { ok: z.boolean() }, annotations: { ...write, destructiveHint: true, idempotentHint: true }, _meta: meta }, input => run("set_course_outline", input, () => "Course draft outline updated."));
 server.registerTool("add_course_lesson", { description: "Create a blank owned lesson draft at the end of an owned course (maximum 100 lessons). Edit with existing lesson tools. Does not publish. Do not automatically retry uncertain success.", inputSchema: { ...course, title: z.string().trim().min(1).max(200).optional() }, outputSchema: { lessonId: ref }, annotations: write, _meta: meta }, input => run("add_course_lesson", input, () => "Lesson draft added."));
 server.registerTool("publish_course", { description: "Publish only the owned course outline and metadata using each lesson’s already published version. Never publishes lesson drafts or changes lesson visibility. Publish lessons explicitly first. Only on explicit user request after review. Private visibility requires Business. Inspect lesson blockers when ok is false; the course remains unchanged. Repeated success creates another snapshot; do not automatically retry.", inputSchema: { ...course, visibility }, outputSchema: { ok: z.boolean(), problems: z.array(z.object({ lessonId: ref, title: z.string(), message: z.string() })).optional() }, annotations: { ...write, destructiveHint: true, openWorldHint: true }, _meta: meta }, input => run("publish_course", input, data => data.ok ? "Course published." : "Course publication needs review."));
 const card = z.object({ id: ref, title: z.string(), description: z.string(), coverUrl: z.string().optional(), lessons: z.number(), visibility, published: z.boolean(), updatedAt: z.number(), archived: z.boolean() });
 server.registerTool("list_courses", { description: "List the connected account's own courses, newest change first, including archived ones (archived true). Returns metadata and lesson counts only. Pages of up to 50; pass nextCursor to continue until it is null.", inputSchema: { limit: z.number().int().min(1).max(50).optional(), cursor: z.string().max(2000).optional() }, outputSchema: { courses: z.array(card), nextCursor: z.string().nullable() }, annotations: read, _meta: meta }, input => run("list_courses", input, d => `${(d.courses as unknown[]).length} course(s).`));
 server.registerTool("set_course_archived", { description: "Archive (archived true) or restore (archived false) an owned course, like the library's archive action. Archiving hides the course from the library and its public page; lessons, drafts and published history are kept. Only on explicit request.", inputSchema: { ...course, archived: z.boolean() }, outputSchema: { ok: z.boolean(), archived: z.boolean() }, annotations: { ...write, destructiveHint: true, idempotentHint: true, openWorldHint: true }, _meta: meta }, input => run("set_course_archived", input, d => d.archived ? "Course archived." : "Course restored."));
 server.registerTool("unpublish_course", { description: "Take an owned published course offline so its public page stops working. Its lessons stay published individually and the draft is kept; publish_course republishes. Only on explicit request.", inputSchema: course, outputSchema: { ok: z.boolean() }, annotations: { ...write, destructiveHint: true, idempotentHint: true, openWorldHint: true }, _meta: meta }, input => run("unpublish_course", input, () => "Course unpublished."));
}
