import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
const ref = z.string().min(1).max(100);
const set = { setId: ref.describe("Flashcard set ID from list_flashcard_sets or create_flashcard_set.") };
const visibility = z.enum(["public", "restricted", "private"]);
const revision = z.number().int().nonnegative().describe("Current revision from get_flashcard_set; reload on conflict before retrying.");
const card = z.object({ id: z.string().regex(/^[A-Za-z0-9_-]{1,100}$/).describe("Stable card ID; keep existing IDs when editing."), front: z.string().trim().min(1).max(2000), back: z.string().trim().min(1).max(4000), conceptIds: z.array(z.string().max(100)).max(20).default([]) });
const cards = z.array(card).max(500);
const status = { revision, visibility, publishedVersionId: ref.nullable(), archived: z.boolean(), updatedAt: z.number() };
const summary = z.object({ setId: ref, title: z.string(), cardCount: z.number(), ...status });
const read = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false };
const write = { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false };
export function registerFlashcardTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
 const meta = { securitySchemes };
 server.registerTool("list_flashcard_sets", { description: "List the connected account's own flashcard sets, newest change first, including archived ones. Card counts only; use get_flashcard_set for the cards. Pages of up to 50; pass nextCursor until it is null.", inputSchema: { limit: z.number().int().min(1).max(50).optional(), cursor: z.string().max(2000).optional() }, outputSchema: { sets: z.array(summary), nextCursor: z.string().nullable() }, annotations: read, _meta: meta }, input => run("list_flashcard_sets", input, d => `${(d.sets as unknown[]).length} flashcard set(s).`));
 server.registerTool("get_flashcard_set", { description: "Read an owned flashcard set's editable draft: title, every card and the revision needed to save, publish or archive it. Owner only.", inputSchema: set, outputSchema: { ...summary.shape, cards: z.array(z.object({ id: z.string(), front: z.string(), back: z.string(), conceptIds: z.array(z.string()) })) }, annotations: read, _meta: meta }, input => run("get_flashcard_set", input, () => "Flashcard set loaded."));
 server.registerTool("create_flashcard_set", { description: "Create a private flashcard set draft with up to 500 cards (front is the prompt, back the answer). Never publishes. Each call creates a new set; check list_flashcard_sets before retrying an uncertain success.", inputSchema: { title: z.string().trim().min(1).max(200), cards }, outputSchema: { setId: ref, revision }, annotations: write, _meta: meta }, input => run("create_flashcard_set", input, () => "Private flashcard set created."));
 server.registerTool("save_flashcard_set", { description: "Replace an owned set's draft title and complete card list with a revision check; omitted cards are removed. Read get_flashcard_set first and keep card IDs. Published versions stay unchanged until publish_flashcard_set. Archived sets must be restored first.", inputSchema: { ...set, expectedRevision: revision, title: z.string().trim().min(1).max(200), cards }, outputSchema: { revision }, annotations: { ...write, destructiveHint: true }, _meta: meta }, input => run("save_flashcard_set", input, () => "Flashcard draft saved."));
 server.registerTool("publish_flashcard_set", { description: "Publish the current draft as a new immutable version with the requested visibility. Only on explicit request after review. Needs at least one card. Returns versionId for attach_lesson_flashcards. Do not automatically retry.", inputSchema: { ...set, expectedRevision: revision, visibility }, outputSchema: { versionId: ref, revision }, annotations: { ...write, openWorldHint: true }, _meta: meta }, input => run("publish_flashcard_set", input, () => "Flashcards published."));
 server.registerTool("set_flashcard_set_lifecycle", { description: "Owner-only, revision-checked: archive hides the set and stops study; restore brings it back; unpublish makes it private and removes the published pointer. History is kept and nothing is deleted. Only on explicit request.", inputSchema: { ...set, expectedRevision: revision, action: z.enum(["archive", "restore", "unpublish"]) }, outputSchema: { revision }, annotations: { ...write, destructiveHint: true, openWorldHint: true }, _meta: meta }, input => run("set_flashcard_set_lifecycle", input, () => "Flashcard set updated."));
 server.registerTool("attach_lesson_flashcards", { description: "Attach a published flashcard version to an owned lesson so learners can study it there (at most 50 per lesson). Use versionId from publish_flashcard_set or publishedVersionId from get_flashcard_set. Attaching the same set again updates its version, label and order. Does not publish the lesson.", inputSchema: { lessonId: ref, versionId: ref, label: z.string().max(200), order: z.number().int().min(0).max(1000) }, outputSchema: { attachmentId: ref }, annotations: { ...write, idempotentHint: true }, _meta: meta }, input => run("attach_lesson_flashcards", input, () => "Flashcards attached to the lesson."));
 server.registerTool("detach_lesson_flashcards", { description: "Remove a flashcard attachment from an owned lesson. The set itself is not changed. Use attachmentId from get_lesson_flashcards.", inputSchema: { attachmentId: ref }, outputSchema: { ok: z.boolean() }, annotations: { ...write, destructiveHint: true, idempotentHint: true }, _meta: meta }, input => run("detach_lesson_flashcards", input, () => "Flashcards detached."));
 server.registerTool("get_lesson_flashcards", { description: "List flashcard sets attached to a lesson you can read, in order, with titles and card counts. Attachments you cannot access are omitted. No card contents.", inputSchema: { lessonId: ref }, outputSchema: { attachments: z.array(z.object({ attachmentId: ref, setId: ref, versionId: ref, title: z.string(), label: z.string(), order: z.number(), cardCount: z.number() })) }, annotations: read, _meta: meta }, input => run("get_lesson_flashcards", input, d => `${(d.attachments as unknown[]).length} attached set(s).`));
}
