import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
export function registerTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
  const formId = z.string().min(1).max(100), read = { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false }, _meta = { securitySchemes };
  server.registerTool("get_form_advanced_analytics", { description: "Owner-only aggregate analytics using the same Chaos UI calculations: correct rates, branching drop-off, completion times, scores, distributions and sampling caveats. Excludes individual written responses and answer keys. Requires authenticated Chaos MCP OAuth access.", inputSchema: { formId }, outputSchema: { analysisJson: z.string(), sampleLimit: z.number() }, annotations: read, _meta }, input=>run("get_form_advanced_analytics", input, ()=>"Advanced analytics loaded."));
  server.registerTool("export_form_responses", { description: "Explicitly export owned respondent data into a downloadable CSV/XLSX/JSON artifact; no response dataset is returned in model context. Download URL is a sensitive bearer link until deletion after 24 hours. Limits: 5000 included responses, 5100 scanned rows, 8 MB scanned data, 16 MB artifact. Export is paginated, not a transaction-wide snapshot; concurrent response edits may appear. Requires authenticated Chaos MCP OAuth access.", inputSchema: { formId, format: z.enum(["csv", "xlsx", "json"]), includePartial: z.boolean().default(false), includeSpam: z.boolean().default(false) }, outputSchema: { downloadUrl: z.string(), filename: z.string(), rows: z.number(), expiresAt: z.number(), byteSize: z.number() }, annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true }, _meta }, input=>run("export_form_responses", input, ()=>"Export download ready; expires in 24 hours."));
  server.registerTool("list_form_collaborators", { description: "Owner-only collaborator list and membership snapshot for guarded access changes. Requires authenticated Chaos MCP OAuth access.", inputSchema: { formId }, outputSchema: { members: z.array(z.object({ id: z.string(), email: z.string(), role: z.enum(["editor", "viewer"]), joined: z.boolean() })), membershipRevision: z.string() }, annotations: read, _meta }, input=>run("list_form_collaborators", input, ()=>"Collaborators loaded."));
  server.registerTool("change_form_collaborator", { description: "Explicit owner-authorized invitation, role change or removal (role=null). Grants access to form and respondent data; may notify an existing Chaos account. Obtain clear user intent identifying recipient and role before calling. Requires current membershipRevision from list_form_collaborators; reload on conflict or uncertain success. Cannot transfer or remove ownership. Requires authenticated Chaos MCP OAuth access.", inputSchema: { formId, email: z.string().email().max(320), role: z.enum(["editor", "viewer"]).nullable(), expectedMembershipRevision: z.string().max(40000) }, outputSchema: { membershipRevision: z.string() }, annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true }, _meta }, input=>run("change_form_collaborator", input, ()=>"Collaborator access updated."));
}
