import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { CallToolResult } from "@modelcontextprotocol/sdk/types.js";
import { z } from "zod";
import { LEARN_LIMITS } from "@/convex/learnModel";

const ref = z.string().min(1).max(100).describe("Raw Chaos lesson/source/version ID from Learn tools.");
const blockId = z.string().regex(/^[A-Za-z0-9_-]{1,100}$/);
const citation = z.object({ sourceId: ref, locator: z.discriminatedUnion("kind", [
  z.object({ kind: z.literal("page"), page: z.number().int().positive() }),
  z.object({ kind: z.literal("slide"), slide: z.number().int().positive() }),
  z.object({ kind: z.literal("time"), start: z.number().nonnegative(), end: z.number().nonnegative().optional() }),
  z.object({ kind: z.literal("section"), label: z.string().min(1).max(300) }),
]) });
const common = { id: blockId, parentId: blockId.optional(), citations: z.array(citation).max(20), conceptIds: z.array(ref).max(20), presentation: z.object({ alignment: z.enum(["left", "center", "right", "justify"]).optional(), textColor: z.string().optional(), backgroundColor: z.string().optional() }).optional() };
const inline = z.object({ text: z.string(), marks: z.object({ bold: z.boolean().optional(), italic: z.boolean().optional(), underline: z.boolean().optional(), strike: z.boolean().optional(), code: z.boolean().optional(), textColor: z.string().optional(), backgroundColor: z.string().optional() }).optional(), href: z.string().optional() });
const text = { ...common, text: z.string().max(LEARN_LIMITS.text), inline: z.array(inline).optional() };
export const learnBlockSchema = z.discriminatedUnion("type", [
  z.object({ ...text, type: z.literal("callout"), tone: z.enum(["info", "tip", "warning", "clinical", "key"]) }),
  z.object({ ...text, type: z.literal("code"), language: z.string() }),
  z.object({ ...text, type: z.literal("quote") }),
  z.object({ ...text, type: z.literal("toggle") }),
  z.object({ ...common, type: z.literal("divider") }),
  z.object({ ...text, type: z.literal("paragraph") }),
  z.object({ ...text, type: z.literal("heading"), level: z.union([z.literal(1), z.literal(2), z.literal(3)]) }),
  z.object({ ...text, type: z.literal("list"), style: z.enum(["bullet", "number", "check"]), checked: z.boolean().optional() }),
  z.object({ ...common, type: z.literal("image"), sourceId: ref, alt: z.string(), caption: z.string(), credit: z.string().optional(), creditUrl: z.string().optional(), figureKind: z.enum(["photo", "diagram"]).optional(), name: z.string().optional(), previewWidth: z.number().positive().max(10000).optional(), showPreview: z.boolean().optional(), annotations: z.object({ v: z.literal(1), items: z.array(z.object({ id: z.string(), x: z.number(), y: z.number(), w: z.number().optional(), h: z.number().optional(), label: z.string(), body: z.string().optional() })) }).optional() }),
  z.object({ ...text, type: z.literal("diagram"), format: z.literal("mermaid") }),
  z.object({ ...common, type: z.literal("youtube"), videoId: z.string().regex(/^[A-Za-z0-9_-]{11}$/), start: z.number().nonnegative().optional(), end: z.number().nonnegative().optional(), caption: z.string() }),
  z.object({ ...text, type: z.literal("equation"), display: z.boolean() }),
  z.object({ ...common, type: z.literal("table"), rows: z.array(z.array(z.string().max(2000)).min(1).max(20)).min(1).max(100), headerRows: z.number().int().min(0).max(100) }),
  z.object({ ...common, type: z.literal("source"), sourceId: ref, label: z.string() }),
  z.object({ ...common, type: z.literal("quiz"), asset: z.discriminatedUnion("kind", [z.object({ kind: z.literal("form"), id: ref }), z.object({ kind: z.literal("quiz"), id: ref })]) }),
]);
const document = z.object({ schemaVersion: z.literal(1), blocks: z.array(learnBlockSchema).max(LEARN_LIMITS.blocks) });
const metadata = z.object({ title: z.string().trim().min(1).max(LEARN_LIMITS.title), description: z.string().max(4000), language: z.string().max(35), tags: z.array(z.string().trim().min(1).max(80)).max(LEARN_LIMITS.tags), license: z.string().max(300).optional(), indexing: z.enum(["index", "noindex"]).optional(), coverUrl: z.string().optional(), authorDisplay: z.string().max(200).optional() });
const visibility = z.enum(["private", "public", "restricted"]);
const revision = z.number().int().nonnegative().describe("Current revision from get_lesson; reload on conflict before retrying.");
const edit = { lessonId: ref, expectedRevision: revision };
const summary = z.object({ lessonId: ref, metadata, revision, status: z.enum(["active", "archived"]), visibility, communityState: z.enum(["ok", "review", "hidden", "removed"]), publishedVersionId: ref.nullable(), updatedAt: z.number() });
const readOutput = summary.extend({ view: z.enum(["draft", "published", "outline"]), versionId: ref.nullable(), document: document.nullable(), outline: z.array(z.object({ id: blockId, parentId: blockId.optional(), type: z.string(), title: z.string() })), totalBlocks: z.number().int(), nextOffset: z.number().int().nullable() });
const operation = z.discriminatedUnion("action", [
  z.object({ action: z.literal("append"), blocks: z.array(learnBlockSchema).min(1).max(LEARN_LIMITS.blocks) }),
  z.object({ action: z.literal("update"), blockId, block: learnBlockSchema }),
  z.object({ action: z.literal("move"), blockId, beforeId: blockId.nullable().describe("Move before this ID; null moves to the end. Parent references must remain valid.") }),
  z.object({ action: z.literal("delete"), blockId }),
]);
const changed = { revision }, created = { lessonId: ref, revision };
const read = { readOnlyHint: true, destructiveHint: false, openWorldHint: false, idempotentHint: true };
const write = { readOnlyHint: false, destructiveHint: false, openWorldHint: false, idempotentHint: false };
export function registerLearnTools(server: McpServer, run: (tool: string, input: Record<string, unknown>, summarize: (data: Record<string, unknown>) => string) => Promise<CallToolResult>, securitySchemes: { type: string; scopes: string[] }[]) {
  const meta = { securitySchemes, "openai/toolInvocation/invoking": "Working in Chaos Learn", "openai/toolInvocation/invoked": "Learn request complete" };
  server.registerTool("get_learn_capabilities", { description: "Discover deployed Chaos lesson schema and enforced block, file, folder and client limits. Requires an active account; returns no content or account data.", inputSchema: {}, outputSchema: { schemaVersion: z.number(), limits: z.record(z.string(), z.number()) }, annotations: read, _meta: meta }, input => run("get_learn_capabilities", input, () => "Learn capabilities loaded."));
  server.registerTool("list_lesson_versions", { description: "Inspect bounded immutable lesson version metadata with edit permission. Follow nextBeforeNumber for history; never alters a draft or publishes.", inputSchema: { lessonId: ref, beforeNumber: z.number().int().positive().optional(), limit: z.number().int().min(1).max(50).optional() }, outputSchema: { versions: z.array(z.object({ versionId: ref, number: z.number(), metadata, publishedAt: z.number(), current: z.boolean() })), nextBeforeNumber: z.number().nullable() }, annotations: read, _meta: meta }, input => run("list_lesson_versions", input, () => "Version history loaded."));
  server.registerTool("get_lesson_version", { description: "Read bounded blocks from an authorized immutable published version. Owners may inspect private history; public readers cannot access historical private versions. Current moderation restrictions always apply.", inputSchema: { lessonId: ref, versionId: ref, offset: z.number().int().min(0).max(500).optional(), limit: z.number().int().min(1).max(100).optional() }, outputSchema: { versionId: ref, metadata, document, totalBlocks: z.number(), nextOffset: z.number().nullable() }, annotations: read, _meta: meta }, input => run("get_lesson_version", input, () => "Lesson version loaded."));
  server.registerTool("list_lessons", { title: "Find lessons", description: "Bounded owned lesson listing or published public lesson search. Public results use published metadata. Owned search matches current draft metadata within bounded indexed pages. Public search indexes published text. Continue partial pages with nextCursor.", inputSchema: { scope: z.enum(["owned", "public"]), query: z.string().max(200).optional(), limit: z.number().int().min(1).max(50).optional(), cursor: z.string().max(2000).optional() }, outputSchema: { items: z.array(summary), nextCursor: z.string().nullable() }, annotations: read, _meta: meta }, input => run("list_lessons", input, d => `${(d.items as unknown[]).length} lessons.`));
  server.registerTool("get_lesson", { title: "Read a lesson", description: "Get at most 100 blocks of a draft, published snapshot or outline. Draft and outlineFrom draft require edit permission. Outline defaults to published. Follow nextOffset for more. No source files or assessment answers.", inputSchema: { lessonId: ref, view: z.enum(["draft", "published", "outline"]), outlineFrom: z.enum(["draft", "published"]).optional(), offset: z.number().int().min(0).max(500).optional(), limit: z.number().int().min(1).max(100).optional() }, outputSchema: readOutput.shape, annotations: read, _meta: meta }, input => run("get_lesson", input, () => "Lesson loaded."));
  server.registerTool("create_lesson", { title: "Create a lesson draft", description: "Create a private lesson draft using Chaos blocks. Citations/assets retain independent permissions. Never publishes or changes source sharing.", inputSchema: { metadata, document: document.optional() }, outputSchema: created, annotations: write, _meta: meta }, input => run("create_lesson", input, () => "Private lesson draft created."));
  server.registerTool("save_lesson_draft", { title: "Replace a lesson draft", description: "Revision-protected replacement of the complete draft; omitted blocks are removed. Read all draft pages first and preserve stable IDs. Keeps a recovery snapshot. Published content stays unchanged until explicit publication.", inputSchema: { ...edit, document, metadata: metadata.optional() }, outputSchema: changed, annotations: { ...write, destructiveHint: true }, _meta: meta }, input => run("save_lesson_draft", input, () => "Lesson draft saved."));
  server.registerTool("edit_lesson_blocks", { title: "Edit lesson blocks", description: "Atomic revision-protected append/update/move/delete operations in supplied order. Update replaces one complete block and preserves its ID. Remove or reparent children before deleting a parent. Final document requires valid parent references without cycles. Never publishes.", inputSchema: { ...edit, operations: z.array(operation).min(1).max(100) }, outputSchema: changed, annotations: { ...write, destructiveHint: true }, _meta: meta }, input => run("edit_lesson_blocks", input, () => "Lesson blocks saved."));
  server.registerTool("publish_lesson", { title: "Publish a lesson", description: "Owner-only explicit immutable publication. Call only when asked to publish; visibility is required. Validates citations, public image access and owned published assessments. Validation problems leave publication unchanged. Does not change source sharing.", inputSchema: { ...edit, visibility, note: z.string().max(2000).optional() }, outputSchema: { ok: z.boolean(), problems: z.array(z.object({ path: z.string(), code: z.string(), message: z.string() })).optional(), versionId: ref.optional(), revision: revision.optional() }, annotations: { ...write, openWorldHint: true }, _meta: meta }, input => run("publish_lesson", input, d => d.ok ? "Lesson published." : "Publication needs fixes."));
  server.registerTool("restore_lesson_version", { title: "Restore a lesson draft", description: "Restore a version belonging to this lesson into the draft with a revision check and recovery snapshot. Does not rewrite history or republish.", inputSchema: { ...edit, versionId: ref }, outputSchema: changed, annotations: { ...write, destructiveHint: true }, _meta: meta }, input => run("restore_lesson_version", input, () => "Version restored to draft."));
  server.registerTool("set_lesson_lifecycle", { title: "Archive or unpublish a lesson", description: "Owner-only revision-protected lifecycle. archive removes public access, preserving content/history; reactivate restores active state; unpublish removes the publication pointer and makes it private. No deletion or new publication.", inputSchema: { ...edit, action: z.enum(["archive", "unpublish", "reactivate"]) }, outputSchema: changed, annotations: { ...write, destructiveHint: true, openWorldHint: true }, _meta: meta }, input => run("set_lesson_lifecycle", input, () => "Lesson lifecycle updated."));
  server.registerTool("fork_lesson", { title: "Fork a published lesson", description: "Copy an accessible immutable version into a new private draft. Non-owners may copy only the current published version. Preserves parent/version/origin and citation IDs; never grants source access or publishes. Each call creates a draft; do not retry an uncertain success.", inputSchema: { lessonId: ref, versionId: ref }, outputSchema: created, annotations: write, _meta: meta }, input => run("fork_lesson", input, () => "Private fork created."));
  server.registerTool("get_learn_source_metadata", { title: "Read source metadata", description: "Independently authorized source metadata only; unavailable when inaccessible. No storage IDs, signed URLs, hashes or file bytes. Metadata visibility never grants content access.", inputSchema: { sourceId: ref }, outputSchema: { available: z.boolean(), source: z.object({ sourceId: ref, metadata: z.object({ title: z.string(), kind: z.enum(["pdf", "slides", "image", "url", "video", "reference", "file"]), origin: z.string(), author: z.string().optional(), url: z.string().optional(), license: z.string().optional() }), metadataVisibility: visibility, contentVisibility: visibility, createdAt: z.number() }).nullable() }, annotations: read, _meta: meta }, input => run("get_learn_source_metadata", input, () => "Source metadata checked."));
  registerLearnAliases(server, run, securitySchemes);
}

function registerLearnAliases(server: McpServer, run: Parameters<typeof registerLearnTools>[1], securitySchemes: { type: string; scopes: string[] }[]) {
  const meta = { securitySchemes, "openai/toolInvocation/invoking": "Working in Chaos Learn", "openai/toolInvocation/invoked": "Learn request complete" };
  server.registerTool("search_lessons", { title: "Search lessons", description: "Search or list owned drafts/current metadata or published public lessons. Bounded indexed cursor pages; follow nextCursor even when a page has no matches. Public search never returns drafts.", inputSchema: { scope: z.enum(["owned", "public"]), query: z.string().max(200).optional(), limit: z.number().int().min(1).max(50).optional(), cursor: z.string().max(2000).optional() }, outputSchema: { items: z.array(summary), nextCursor: z.string().nullable() }, annotations: read, _meta: meta }, input => run("search_lessons", input, () => "Lesson search complete."));
  server.registerTool("get_lesson_outline", { title: "Read a lesson outline", description: "Read a bounded outline of the current published snapshot, or set outlineFrom draft with edit permission. Follow nextOffset for more; no source files or quiz answers.", inputSchema: { lessonId: ref, outlineFrom: z.enum(["draft", "published"]).optional(), offset: z.number().int().min(0).max(500).optional(), limit: z.number().int().min(1).max(100).optional() }, outputSchema: readOutput.shape, annotations: read, _meta: meta }, input => run("get_lesson_outline", input, () => "Lesson outline loaded."));
  const source = z.object({ sourceId: ref, metadata: z.object({ title: z.string(), kind: z.enum(["pdf", "slides", "image", "url", "video", "reference", "file"]), origin: z.string(), author: z.string().optional(), url: z.string().optional(), license: z.string().optional() }), metadataVisibility: visibility, contentVisibility: visibility, createdAt: z.number() });
  server.registerTool("get_lesson_sources", { title: "Read a lesson's source metadata", description: "Read only sources cited or embedded in the selected draft or current published snapshot, at most 50. Draft requires edit permission. Independently checks source metadata permission and omits inaccessible sources. Never returns file bytes, storage IDs, hashes or signed URLs, and never grants content access.", inputSchema: { lessonId: ref, view: z.enum(["draft", "published"]) }, outputSchema: { sources: z.array(source).max(50) }, annotations: read, _meta: meta }, input => run("get_lesson_sources", input, () => "Lesson source metadata loaded."));
  server.registerTool("add_lesson_blocks", { title: "Append lesson blocks", description: "Append complete Chaos blocks to a draft with a mandatory revision check. New IDs must be unique and stable. No publication. Use move_lesson_blocks afterwards to position them, or edit_lesson_blocks for an atomic append-and-move batch.", inputSchema: { ...edit, blocks: z.array(learnBlockSchema).min(1).max(LEARN_LIMITS.blocks) }, outputSchema: changed, annotations: write, _meta: meta }, input => run("add_lesson_blocks", input, () => "Blocks appended."));
  server.registerTool("update_lesson_blocks", { title: "Update lesson blocks", description: "Revision-protected atomic replacement of the named existing blocks only. Each complete block's stable ID identifies the block to replace. Other blocks are preserved. Never publishes.", inputSchema: { ...edit, blocks: z.array(learnBlockSchema).min(1).max(100) }, outputSchema: changed, annotations: { ...write, destructiveHint: true }, _meta: meta }, input => run("update_lesson_blocks", input, () => "Blocks updated."));
  server.registerTool("move_lesson_blocks", { title: "Move lesson blocks", description: "Revision-protected atomic moves in supplied order. beforeId names the destination; null moves to the end. Preserves block contents and IDs; no publication.", inputSchema: { ...edit, moves: z.array(z.object({ blockId, beforeId: blockId.nullable() })).min(1).max(100) }, outputSchema: changed, annotations: write, _meta: meta }, input => run("move_lesson_blocks", input, () => "Blocks moved."));
  server.registerTool("delete_lesson_blocks", { title: "Delete lesson blocks from draft", description: "Revision-protected atomic deletion of existing IDs from the draft, keeping a recovery snapshot. Remove children before parents or use edit_lesson_blocks to reparent them first. Published history stays unchanged; never publishes.", inputSchema: { ...edit, blockIds: z.array(blockId).min(1).max(100) }, outputSchema: changed, annotations: { ...write, destructiveHint: true }, _meta: meta }, input => run("delete_lesson_blocks", input, () => "Blocks removed from draft."));
}
