import { McpToolError } from "./errors";
const MCP_PERMISSIONS = ["read_content", "edit_content", "publish_content", "aggregate_analytics", "individual_responses", "collaborators", "destructive", "admin_crm", "admin_operations"] as const;
export type McpPermission = (typeof MCP_PERMISSIONS)[number];
/** Every registry and composed-workflow operation needs an explicit reviewed category. */
const TOOL_PERMISSIONS = {
  accept_team_invitation: "collaborators",
  add_course_lesson: "edit_content",
  add_crm_note: "admin_crm",
  add_folder_member: "edit_content",
  add_lesson_blocks: "edit_content",
  advance_game: "edit_content",
  attach_lesson_flashcards: "edit_content",
  attach_lesson_quiz: "edit_content",
  build_study_lesson: "edit_content",
  change_form_collaborator: "collaborators",
  change_team_member_role: "collaborators",
  checkpoint_study_lesson: "edit_content",
  complete_crm_follow_up: "admin_crm",
  create_course: "edit_content",
  create_flashcard_set: "edit_content",
  create_folder: "edit_content",
  create_form: "edit_content",
  create_full_course: "edit_content",
  create_game_draft: "edit_content",
  create_lesson: "edit_content",
  create_lesson_curriculum_mapping: "edit_content",
  create_lesson_live_game: "edit_content",
  create_team: "edit_content",
  customize_my_card: "edit_content",
  delete_lesson_blocks: "destructive",
  detach_lesson_flashcards: "edit_content",
  edit_lesson_blocks: "destructive",
  end_game: "destructive",
  export_course_manifest: "read_content",
  export_form_responses: "individual_responses",
  finalize_study_lesson: "edit_content",
  fork_lesson: "edit_content",
  fork_quiz: "edit_content",
  get_admin_overview: "admin_operations",
  get_course: "read_content",
  get_course_lesson: "read_content",
  get_course_progress: "read_content",
  get_crm_activity: "admin_crm",
  get_crm_contact: "admin_crm",
  get_flashcard_set: "read_content",
  get_form: "read_content",
  get_form_advanced_analytics: "aggregate_analytics",
  get_form_response_controls: "read_content",
  get_game: "read_content",
  get_learn_capabilities: "read_content",
  get_learn_source_metadata: "read_content",
  get_lesson: "read_content",
  get_lesson_flashcards: "read_content",
  get_lesson_glossary: "read_content",
  get_lesson_outline: "read_content",
  get_lesson_progress: "read_content",
  get_lesson_quizzes: "read_content",
  get_lesson_sources: "read_content",
  get_lesson_version: "read_content",
  get_my_card: "read_content",
  get_public_card: "read_content",
  get_quiz_fork_lineage: "read_content",
  get_results: "aggregate_analytics",
  get_student_card_preferences: "read_content",
  get_student_card_visibility: "read_content",
  get_study_lesson_checkpoint: "read_content",
  get_study_lesson_job: "read_content",
  get_study_lesson_skill: "read_content",
  get_study_source_content: "read_content",
  get_weak_area_actions: "read_content",
  host_game: "publish_content",
  import_course_lesson: "edit_content",
  invite_team_member: "collaborators",
  list_admin_activity: "admin_operations",
  list_admin_content: "admin_operations",
  list_admin_learning_content: "admin_operations",
  list_admin_teams: "admin_operations",
  list_admin_users: "admin_operations",
  list_courses: "read_content",
  list_crm_contacts: "admin_crm",
  list_curriculum_institutions: "read_content",
  list_curriculum_nodes: "read_content",
  list_curriculum_programs: "read_content",
  list_curriculum_versions: "read_content",
  list_documentation: "admin_operations",
  list_flashcard_sets: "read_content",
  list_folder_contents: "read_content",
  list_folders: "read_content",
  list_form_collaborators: "collaborators",
  list_games: "read_content",
  list_lesson_curriculum_mappings: "read_content",
  list_lesson_versions: "read_content",
  list_lessons: "read_content",
  list_my_students: "individual_responses",
  list_public_authors: "read_content",
  list_public_student_cards: "read_content",
  list_responses: "individual_responses",
  list_team_invitations: "read_content",
  list_team_members: "read_content",
  list_team_resources: "read_content",
  list_teams: "read_content",
  list_themes: "read_content",
  moderate_admin_content: "admin_operations",
  moderate_admin_user: "admin_operations",
  move_folder: "edit_content",
  move_lesson_blocks: "edit_content",
  publish_course: "publish_content",
  publish_flashcard_set: "publish_content",
  publish_form: "publish_content",
  publish_lesson: "publish_content",
  publish_study_lesson: "publish_content",
  publish_study_source: "publish_content",
  refresh_admin_analytics: "admin_operations",
  refresh_study_lesson_placement: "edit_content",
  register_study_reference: "edit_content",
  remember_course: "edit_content",
  remove_team_member: "collaborators",
  rename_team: "edit_content",
  restart_lesson_progress: "destructive",
  restore_lesson_version: "destructive",
  revoke_team_invitation: "collaborators",
  save_crm_contact: "admin_crm",
  save_documentation: "admin_operations",
  save_flashcard_set: "edit_content",
  save_lesson: "edit_content",
  save_lesson_draft: "edit_content",
  search_curriculum_modules: "read_content",
  search_forms: "read_content",
  search_learn_directory: "read_content",
  search_lessons: "read_content",
  set_author_listing_visibility: "edit_content",
  set_course_archived: "destructive",
  set_course_modules: "edit_content",
  set_course_outline: "edit_content",
  set_crm_contact_stages: "admin_crm",
  set_flashcard_set_lifecycle: "destructive",
  set_form_branching: "edit_content",
  set_form_response_controls: "edit_content",
  set_form_sound: "edit_content",
  set_form_status: "destructive",
  set_form_theme: "edit_content",
  set_game_settings: "edit_content",
  set_lesson_glossary: "edit_content",
  set_lesson_lifecycle: "destructive",
  set_student_card_preferences: "edit_content",
  set_student_card_visibility: "edit_content",
  set_study_teaching_profile: "edit_content",
  share_with_team: "collaborators",
  unpublish_course: "destructive",
  unshare_from_team: "collaborators",
  update_course: "edit_content",
  update_form: "edit_content",
  update_lesson_blocks: "edit_content",
  upload_study_source: "edit_content",
  upsert_form_file_question: "edit_content",
} as const satisfies Record<string, McpPermission>;

/** Unknown operations fail closed, including when no granular allow-list was supplied. */
export function permissionForTool(tool: string): McpPermission {
  if (!Object.hasOwn(TOOL_PERMISSIONS, tool)) {
    throw new McpToolError("PERMISSION_DENIED", `MCP tool ${tool} has no permission classification.`);
  }
  return TOOL_PERMISSIONS[tool as keyof typeof TOOL_PERMISSIONS];
}
export function requireToolPermission(tool: string, allowed?: readonly McpPermission[]) {
 const category = permissionForTool(tool);
 if (allowed && !allowed.includes(category)) throw new McpToolError("PERMISSION_DENIED", `This connection does not allow ${category}.`);
}
