import { describe, expect, it } from "vitest";
import { api } from "../../convex/_generated/api";
import { makeFunctionReference } from "convex/server";
import { defaultFormSettings } from "../../convex/formModel";
import { emptyDefinition } from "../../convex/formLogic";
import { captureTypedHidden, checkHiddenParameters } from "../../convex/formRespondent";
import { formResponseData } from "../../convex/webhookEvents";
import { createTestConvex } from "./setup";
import { creatorIdentity } from "../fixtures";
const definitions = [{ name: "cohort", type: "number" as const, required: true }, { name: "consent", type: "boolean" as const }, { name: "campaign", type: "string" as const }];
describe("typed hidden URL parameters", () => {
  it("rejects ambiguous coercions with parameter-specific errors", () => {
    for (const cohort of ["", " 2", "NaN", "Infinity", "0x10", "01"]) expect(() => captureTypedHidden(definitions, { cohort })).toThrow(/cohort/);
    expect(() => captureTypedHidden(definitions, { cohort: "2", consent: "yes" })).toThrow(/consent/);
    expect(() => captureTypedHidden(definitions, {})).toThrow(/cohort/);
    expect(captureTypedHidden(definitions, { cohort: "2.5", consent: "false", campaign: " x " })).toEqual({ cohort: 2.5, consent: false, campaign: " x " });
    expect(() => checkHiddenParameters(definitions, ["COHORT"])).toThrow(/twice/);
    expect(() => checkHiddenParameters(Array.from({ length: 21 }, (_, i) => ({ name: `p${i}`, type: "string" })))).toThrow(/20/);
  });
  it("persists typed metadata alongside legacy strings, exports and scoped webhooks", async () => {
    const t = createTestConvex(), owner = t.withIdentity(creatorIdentity);
    await owner.mutation(api.quizFunctions.getOrCreateUser, {});
    const definition = emptyDefinition("Typed metadata");
    definition.fields = [{ id: "cohort", type: "text", label: "Answer", required: false }];
    const formId = await owner.mutation(api.forms.createForm, { definition });
    const form = (await owner.query(api.forms.getFormForEditor, { formId }))!;
    await owner.mutation(api.forms.publishForm, { formId, expectedRevision: form.draftRevision });
    await owner.mutation(api.forms.updateFormSettings, { formId, settings: { ...defaultFormSettings, hiddenFields: ["legacy"], hiddenParameters: definitions } });
    const args = { shareId: form.shareId, submissionKey: "typed-hidden-123", answers: { cohort: "question answer" }, language: "en" as const, final: true, startedAt: Date.now() - 10000, hidden: { cohort: "2026", consent: "false", legacy: " old ", ignored: "secret" } };
    await expect(t.mutation(api.respond.submitResponse, { ...args, hidden: { cohort: "oops" } })).rejects.toThrow(/cohort/);
    const result = await t.mutation(api.respond.submitResponse, args);
    const row = (await t.run(ctx => ctx.db.get("formResponses", result.responseId)))!;
    expect(row.typedHidden).toEqual({ cohort: 2026, consent: false }); expect(row.hidden).toEqual({ legacy: "old" }); expect(row.answers.cohort).toBe("question answer");
    const listResponses = makeFunctionReference<"query">("mcp:listResponses");
    const mcpArgs = { userId: creatorIdentity.subject, id: `form_${formId}` };
    const mcp = await t.query(listResponses, mcpArgs);
    expect(mcp.responses).toHaveLength(1);
    expect(mcp.responses[0]).toMatchObject({ hidden: { legacy: "old" }, typedHidden: { cohort: 2026, consent: false }, answers: { Answer: "question answer" } });
    expect(JSON.stringify(mcp)).not.toContain("secret");
    await expect(t.query(listResponses, { ...mcpArgs, userId: "unrelated-account" })).rejects.toThrow("NOT_FOUND");
    await t.run(ctx => ctx.db.patch("formResponses", result.responseId, { hidden: undefined, typedHidden: undefined }));
    const legacy = await t.query(listResponses, mcpArgs);
    expect(legacy.responses[0]).not.toHaveProperty("hidden");
    expect(legacy.responses[0]).not.toHaveProperty("typedHidden");
    expect(legacy.responses[0].answers).toEqual(mcp.responses[0].answers);
    await t.run(ctx => ctx.db.patch("formResponses", result.responseId, { hidden: row.hidden, typedHidden: row.typedHidden }));
    const retry = await t.mutation(api.respond.submitResponse, { ...args, hidden: { cohort: "999" } });
    expect(retry.responseId).toBe(result.responseId);
    const exported = await owner.query(api.formResults.exportResponses, { formId, includePartial: false, includeSpam: true, paginationOpts: { cursor: null, numItems: 10 } });
    expect(exported!.rows[0].hidden).toEqual({ legacy: "old", cohort: 2026, consent: false });
    const storedForm = (await t.run(ctx => ctx.db.get("forms", formId)))!;
    const event = formResponseData(storedForm, row, definition);
    expect(JSON.stringify(event.base)).not.toContain("typedHidden");
    expect(event.withAnswers?.typedHidden).toEqual({ cohort: 2026, consent: false });
    // Five identical records satisfy the existing small-cell suppression rule.
    for (let i = 0; i < 4; i++) await t.mutation(api.respond.submitResponse, { ...args, submissionKey: `typed-hidden-extra-${i}` });
    const analysis = await owner.query(makeFunctionReference<"query">("formSegmentAnalysis:crossTab"), { formId, version: 1, segment: { kind: "hidden_parameter", name: "consent", values: [false, true] }, compare: { kind: "status" } });
    expect(analysis.suppressed).toBe(false);
    expect(analysis.cells).toEqual([{ segment: "false", comparison: "completed", count: 5, withinSegmentRate: 1 }]);
  });
});
