/** Buttons outside the sidebar (the docs home hero) open the docs search by sending this window event. */
export const OPEN_DOCS_SEARCH = "chaos:open-docs-search";

/** Interface text for the docs pages. The articles themselves live in lib/docs. */
export const docsCopy = {
  en: {
    docs: "Docs",
    brand: "Chaos",
    searchPlaceholder: "Search the docs",
    searchLabel: "Search the docs",
    resultsLabel: "Search results",
    noResults: (query: string) => `Nothing matches “${query}”. Try another word.`,
    noResultsTitle: "No results",
    close: "Close search",
    preview: "Preview",
    openChaos: "Open Chaos",
    guides: "All guides",
    navLabel: "Documentation",
    onThisPage: "On this page",
    previous: "Previous",
    next: "Next",
    indexTitle: "How to use Chaos",
    indexLead: "Step-by-step guides for forms, quizzes and live games, plus the API, webhooks and self-hosting.",
    otherLanguage: "العربية",
    otherLanguageLabel: "Read in Arabic",
    articlesCount: (n: number) => `${n} ${n === 1 ? "article" : "articles"}`,
  },
  ar: {
    docs: "الدليل",
    brand: "Chaos",
    searchPlaceholder: "ابحث في الدليل",
    searchLabel: "ابحث في الدليل",
    resultsLabel: "نتائج البحث",
    noResults: (query: string) => `لا شيء يطابق «${query}». جرّب كلمة أخرى.`,
    noResultsTitle: "لا نتائج",
    close: "أغلق البحث",
    preview: "معاينة",
    openChaos: "افتح Chaos",
    guides: "كل الأدلة",
    navLabel: "الدليل",
    onThisPage: "في هذه الصفحة",
    previous: "السابق",
    next: "التالي",
    indexTitle: "كيف تستخدم Chaos",
    indexLead: "أدلة خطوة بخطوة للنماذج والاختبارات والألعاب المباشرة، ومعها الـ API والـ webhooks والاستضافة الذاتية.",
    otherLanguage: "English",
    otherLanguageLabel: "Read in English",
    articlesCount: (n: number) => (n === 1 ? "مقال واحد" : n === 2 ? "مقالان" : n <= 10 ? `${n} مقالات` : `${n} مقالًا`),
  },
};
