export const homeworkCopy = {
  en: {
    title: "Homework", back: "Back to results", loading: "Loading homework…", unavailable: "This form is unavailable.", ownerOnly: "Only the form owner can create homework.", published: "Publish a quiz before creating homework.", create: "Create assignment", creating: "Creating…", name: "Assignment title", version: "Published version", opens: "Opens", deadline: "Deadline", attempts: "Maximum attempts", pinned: "Students answer the selected published version, even if you publish changes later.", saved: "Assignment created. Enroll students before sharing the link.", link: "Student link", copy: "Copy link", copied: "Link copied.", existing: "Manage an existing assignment", assignmentId: "Assignment ID", manage: "Manage assignment", student: "Student account ID", studentHint: "Use the registered account ID supplied by the student.", enroll: "Enroll student", revoke: "Revoke enrollment", report: "Show attempts", close: "Close assignment", reopen: "Reopen assignment", updated: "Assignment updated.", enrolled: "Enrollment updated.", history: "Attempts", none: "No attempts yet.", number: "Attempt", started: "Started", submitted: "Submitted", score: "Score", pending: "In progress", signIn: "Sign in to do your homework", signInHelp: "Use the account your teacher enrolled.", start: "Start or resume attempt", busy: "Please wait…", refresh: "Refresh questions", due: "Due", remaining: "Attempts remaining", submit: "Submit homework", done: "Homework submitted", language: "Answer language", expired: "The deadline has passed. Submissions and uploads are closed.", failure: "Could not complete this action. Check your connection and try again.", notOpen: "This assignment is closed, has not opened yet, or its deadline has passed.", enrollment: "An active enrollment is required. Ask your teacher to check your account.", limit: "No more attempts are available.", invalid: "Check your answers and try again.", upload: "Upload failed. Try again.", fileSize: "Upload a nonempty file of at most 10 MB.", dates: "Choose valid dates with the deadline after the opening time and in the future.", quiz: "The selected version must be a published quiz.", invalidId: "Enter a valid assignment ID.", refreshHelp: "Refresh to check for newly released questions. Your current answers are kept.", noQuestions: "No questions have been released yet.", backHome: "Chaos",
  },
  ar: {
    title: "الواجب", back: "العودة إلى النتائج", loading: "جارٍ تحميل الواجب…", unavailable: "هذا النموذج غير متاح.", ownerOnly: "مالك النموذج فقط يمكنه إنشاء واجب.", published: "انشر اختبارًا قبل إنشاء واجب.", create: "إنشاء واجب", creating: "جارٍ الإنشاء…", name: "عنوان الواجب", version: "النسخة المنشورة", opens: "موعد الفتح", deadline: "الموعد النهائي", attempts: "الحد الأقصى للمحاولات", pinned: "يجيب الطلاب عن النسخة المنشورة المختارة، حتى لو نشرت تعديلات لاحقًا.", saved: "تم إنشاء الواجب. سجّل الطلاب قبل مشاركة الرابط.", link: "رابط الطالب", copy: "نسخ الرابط", copied: "تم نسخ الرابط.", existing: "إدارة واجب موجود", assignmentId: "معرّف الواجب", manage: "إدارة الواجب", student: "معرّف حساب الطالب", studentHint: "استخدم معرّف الحساب المسجل الذي يقدمه الطالب.", enroll: "تسجيل الطالب", revoke: "إلغاء التسجيل", report: "عرض المحاولات", close: "إغلاق الواجب", reopen: "إعادة فتح الواجب", updated: "تم تحديث الواجب.", enrolled: "تم تحديث التسجيل.", history: "المحاولات", none: "لا توجد محاولات بعد.", number: "المحاولة", started: "بدأت", submitted: "أُرسلت", score: "الدرجة", pending: "قيد الإجابة", signIn: "سجّل الدخول للإجابة عن واجبك", signInHelp: "استخدم الحساب الذي سجّله معلمك.", start: "بدء المحاولة أو متابعتها", busy: "يرجى الانتظار…", refresh: "تحديث الأسئلة", due: "الموعد النهائي", remaining: "المحاولات المتبقية", submit: "إرسال الواجب", done: "تم إرسال الواجب", language: "لغة الإجابة", expired: "انتهى الموعد النهائي. أُغلق الإرسال ورفع الملفات.", failure: "تعذر إكمال الإجراء. تحقق من اتصالك وحاول مجددًا.", notOpen: "هذا الواجب مغلق، أو لم يفتح بعد، أو انتهى موعده.", enrollment: "يلزم تسجيل نشط. اطلب من معلمك التحقق من حسابك.", limit: "لا توجد محاولات أخرى متاحة.", invalid: "تحقق من إجاباتك وحاول مجددًا.", upload: "تعذر رفع الملف. حاول مجددًا.", fileSize: "ارفع ملفًا غير فارغ لا يتجاوز 10 ميغابايت.", dates: "اختر مواعيد صالحة بحيث يكون الموعد النهائي بعد الفتح وفي المستقبل.", quiz: "يجب أن تكون النسخة المختارة اختبارًا منشورًا.", invalidId: "أدخل معرّف واجب صالحًا.", refreshHelp: "حدّث للتحقق من الأسئلة التي أُتيحت حديثًا. ستبقى إجاباتك الحالية.", noQuestions: "لم تُتح أي أسئلة بعد.", backHome: "Chaos",
  },
};

export function homeworkError(error: unknown, t: typeof homeworkCopy.en): string {
  const message = error instanceof Error ? error.message : "";
  if (/Assignment not open/.test(message)) return t.notOpen;
  if (/enrollment/.test(message)) return t.enrollment;
  if (/limit reached|Attempt unavailable/.test(message)) return t.limit;
  if (/VALIDATION_FAILED/.test(message)) return t.invalid;
  return t.failure;
}
