"use client";
import { useState } from "react";
import { useLocale } from "@/lib/i18n";
import { exampleLesson, exampleCards } from "@/lib/learn/exampleLesson";
import { fromDurableDocument } from "@/lib/learn/chaosDocument";
import BlockRenderer from "@/components/learn/reader/BlockRenderer";
import { StudyRound } from "@/components/learn/study/FlashcardStudy";
import CompletionAction from "@/components/learn/reader/CompletionAction";
import FormRenderer from "@/components/forms/FormRenderer";
import { emptyDefinition, type Answers } from "@/convex/formLogic";
import { LessonActivity } from "@/components/learn/reader/ActivityContext";
import Link from "./SiteLink";
export default function LearnExample() {
 const { locale } = useLocale(), ar = locale === "ar";
 const [phone, setPhone] = useState(false), [reviews, setReviews] = useState<{cardId:string;box:number;reviewedAt:number}[]>([]), [cardsDone,setCardsDone] = useState(false), [answers,setAnswers] = useState<Answers>({}), [checked,setChecked] = useState(false), [complete,setComplete] = useState(false), [run,setRun] = useState(0);
 const quiz = emptyDefinition(ar ? "اختبار قصير" : "Checkpoint"); quiz.presentation="page"; quiz.fields=[{ id:"q",type:"choice",label:ar ? "ماذا تفعل بعد القراءة؟" : "What should you do after reading?",required:true,options:[{id:"recall",label:ar ? "استرجع من الذاكرة" : "Recall from memory"},{id:"repeat",label:ar ? "أعد القراءة فقط" : "Only read again"}]}];
 return <section className="workspace-ui lx-section site-learn-example" aria-label={ar ? "مثال درس تفاعلي" : "Interactive lesson example"}><div className="lx-actions"><h2>{ar ? "جرّب درسًا حقيقيًا" : "Try a real lesson"}</h2><button type="button" className="ws-btn" aria-pressed={phone} onClick={() => setPhone(!phone)}>{ar ? "عرض الهاتف" : "Phone view"}</button></div><p className="lx-notice">{ar ? "مثال باستخدام مكونات Chaos. الإجابات والتقدم في هذه المعاينة فقط." : "A sample built with Chaos components. Answers and progress stay in this preview."}</p><div className="site-learn-example__reader" data-phone={phone || undefined}><div className="lx-course-meter" role="progressbar" aria-label={ar ? "تقدم المثال" : "Example progress"} aria-valuemin={0} aria-valuemax={3} aria-valuenow={Number(cardsDone)+Number(checked)+Number(complete)}><span style={{width:`${(Number(cardsDone)+Number(checked)+Number(complete))/3*100}%`}} /></div><article className="lx-article"><BlockRenderer content={fromDurableDocument(exampleLesson)} sources={[]} /><LessonActivity.Provider value={() => setCardsDone(true)}><StudyRound key={run} setId="example" cards={exampleCards} reviews={reviews} onReview={async (cardId,knew) => setReviews(old => [...old.filter(r => r.cardId!==cardId),{cardId,box:knew?3:1,reviewedAt:Date.now()}])} /></LessonActivity.Provider>{!checked ? <FormRenderer definition={quiz} language={locale} answers={answers} onAnswer={(id,value) => setAnswers(old => { const next = {...old}; if(value === undefined) delete next[id]; else next[id] = value; return next; })} onSubmit={() => setChecked(true)} submitLabel={ar ? "تحقق من الإجابة" : "Check answer"} /> : <p role="status">{answers.q==="recall" ? (ar ? "صحيح. حاول الاسترجاع من الذاكرة." : "Correct. Try recalling from memory.") : (ar ? "حاول الاسترجاع من الذاكرة أولًا." : "Try recalling from memory first.")}</p>}<CompletionAction completed={complete} disabled={!cardsDone||!checked} onComplete={async () => setComplete(true)} onReset={async () => { setComplete(false);setChecked(false);setCardsDone(false);setReviews([]);setAnswers({});setRun(r=>r+1); }} />{complete && <Link className="ws-btn ws-btn--primary" href="/learn">{ar ? "تابع التعلّم" : "Continue learning"}</Link>}</article></div></section>;
}
