"use client";
import { useEffect, useState } from "react";
import { useLocale } from "@/lib/i18n";
import Link from "./SiteLink";
export default function McpWorkflowDemo() {
 const { locale } = useLocale(), ar=locale==="ar", [step,setStep]=useState(0), [playing,setPlaying]=useState(false);
 const steps=ar ? ["أرفق ملفك في مساعدك", "أنشئ مسودة الدرس من الملف", "أضف البطاقات بعد الفقرة", "راجع المسودة في Chaos"] : ["Attach your PDF in your assistant", "Create a lesson draft from the PDF", "Insert flashcards after the section", "Review the draft in Chaos"];
 useEffect(() => { if(!playing) return; if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setStep(3);setPlaying(false);return;} const timer=setInterval(()=>setStep(s=>{if(s===3){setPlaying(false);return s;}return s+1;}),1600);return()=>clearInterval(timer); },[playing]);
 return <section className="site-section site-mcp-demo"><h2 className="site-h2">{ar ? "شاهد الملف يتحوّل إلى درس" : "See notes become a lesson"}</h2><p>{ar ? "عرض توضيحي لمسار العمل المدعوم. اربط مساعدك لتنفيذه بملفك؛ لا تُجرى هنا أي كتابة في حسابك." : "An illustration of the supported workflow. Connect your assistant to run it with your PDF; this preview makes no account changes."}</p><div className="site-mcp-demo__panes"><div><h3>ChatGPT / Claude</h3><blockquote>{ar ? "أنشئ المحاضرة الثانية من هذا الملف وأضف ٢٥ بطاقة بعد قسم الأعصاب القحفية." : "Make Lecture 2 from this PDF and add 25 flashcards after the cranial nerves section."}</blockquote><ol>{steps.map((s,i)=><li key={s} data-active={i<=step}>{s}</li>)}</ol></div><div className="site-mcp-demo__draft" aria-live="polite"><h3>Chaos · {ar ? "مسودة" : "Draft"}</h3>{step>0 && <><h4>{ar ? "المحاضرة الثانية" : "Lecture 2"}</h4><p>{ar ? "نص الدرس من ملفك" : "Lesson text from your PDF"}</p><h4>{ar ? "الأعصاب القحفية" : "Cranial nerves"}</h4></>}{step>1 && <div className="lx-inline-flashcards"><strong>{ar ? "بطاقات مرتبطة · ٢٥ بطاقة" : "Referenced flashcards · 25 cards"}</strong><p>{ar ? "تُضاف هنا بعد الفقرة" : "Inserted here after the section"}</p></div>}{step===3 && <p>{ar ? "جاهز للمراجعة. النشر خطوة مستقلة." : "Ready to review. Publication is a separate step."}</p>}</div></div><div className="site-hero__actions"><button type="button" className="site-btn" disabled={playing} onClick={()=>{setStep(0);setPlaying(true);}}>{ar ? "شغّل العرض" : "Play workflow"}</button><button type="button" className="site-btn site-btn--ghost" disabled={playing} onClick={()=>setStep(s=>(s+1)%4)}>{ar ? "الخطوة التالية" : "Next step"}</button><Link className="site-btn site-btn--primary" href="/connect">{ar ? "اربط مساعدك" : "Connect your assistant"}</Link></div><details><summary>{ar ? "الأدوات المستخدمة" : "Tools behind the workflow"}</summary><p><code>create_lesson → save_lesson_draft → create_flashcard_set → edit_lesson_blocks</code></p><p>{ar ? "تُراجع المصادر والبطاقات قبل نشرها صراحةً." : "Review sources and cards before explicitly publishing each asset."}</p></details></section>;
}
