// Generated by scripts/generate-auth-schema.mjs.
// Preserve upstream index names: the Better Auth adapter selects these by field.
/* eslint-disable @convex-dev/no-duplicate-indexes */
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";
const baseTables = {
  user: defineTable({
    name: v.string(),
    email: v.string(),
    emailVerified: v.boolean(),
    image: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
    twoFactorEnabled: v.optional(v.union(v.null(), v.boolean())),
    isAnonymous: v.optional(v.union(v.null(), v.boolean())),
    username: v.optional(v.union(v.null(), v.string())),
    displayUsername: v.optional(v.union(v.null(), v.string())),
    phoneNumber: v.optional(v.union(v.null(), v.string())),
    phoneNumberVerified: v.optional(v.union(v.null(), v.boolean())),
    userId: v.optional(v.union(v.null(), v.string())),
  })
    .index("email_name", ["email","name"])
    .index("name", ["name"])
    .index("userId", ["userId"])
    .index("username", ["username"])
    .index("phoneNumber", ["phoneNumber"]),
  session: defineTable({
    expiresAt: v.number(),
    token: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    ipAddress: v.optional(v.union(v.null(), v.string())),
    userAgent: v.optional(v.union(v.null(), v.string())),
    userId: v.string(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("expiresAt_userId", ["expiresAt","userId"])
    .index("token", ["token"])
    .index("userId", ["userId"]),
  account: defineTable({
    accountId: v.string(),
    providerId: v.string(),
    userId: v.string(),
    accessToken: v.optional(v.union(v.null(), v.string())),
    refreshToken: v.optional(v.union(v.null(), v.string())),
    idToken: v.optional(v.union(v.null(), v.string())),
    accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    scope: v.optional(v.union(v.null(), v.string())),
    password: v.optional(v.union(v.null(), v.string())),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("accountId", ["accountId"])
    .index("accountId_providerId", ["accountId","providerId"])
    .index("providerId_userId", ["providerId","userId"])
    .index("userId", ["userId"]),
  verification: defineTable({
    identifier: v.string(),
    value: v.string(),
    expiresAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("expiresAt", ["expiresAt"])
    .index("identifier", ["identifier"]),
  twoFactor: defineTable({
    secret: v.string(),
    backupCodes: v.string(),
    userId: v.string(),
    verified: v.optional(v.union(v.null(), v.boolean())),
  })
    .index("userId", ["userId"]),
  oauthApplication: defineTable({
    name: v.optional(v.union(v.null(), v.string())),
    icon: v.optional(v.union(v.null(), v.string())),
    metadata: v.optional(v.union(v.null(), v.string())),
    clientId: v.optional(v.union(v.null(), v.string())),
    clientSecret: v.optional(v.union(v.null(), v.string())),
    redirectUrls: v.optional(v.union(v.null(), v.string())),
    type: v.optional(v.union(v.null(), v.string())),
    disabled: v.optional(v.union(v.null(), v.boolean())),
    userId: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
  })
    .index("clientId", ["clientId"])
    .index("userId", ["userId"]),
  oauthAccessToken: defineTable({
    accessToken: v.optional(v.union(v.null(), v.string())),
    refreshToken: v.optional(v.union(v.null(), v.string())),
    accessTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    refreshTokenExpiresAt: v.optional(v.union(v.null(), v.number())),
    clientId: v.optional(v.union(v.null(), v.string())),
    userId: v.optional(v.union(v.null(), v.string())),
    scopes: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
  })
    .index("accessToken", ["accessToken"])
    .index("refreshToken", ["refreshToken"])
    .index("clientId", ["clientId"])
    .index("userId", ["userId"]),
  oauthConsent: defineTable({
    clientId: v.optional(v.union(v.null(), v.string())),
    userId: v.optional(v.union(v.null(), v.string())),
    scopes: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
    consentGiven: v.optional(v.union(v.null(), v.boolean())),
  })
    .index("clientId_userId", ["clientId","userId"])
    .index("userId", ["userId"]),
  jwks: defineTable({
    publicKey: v.string(),
    privateKey: v.string(),
    createdAt: v.number(),
    expiresAt: v.optional(v.union(v.null(), v.number())),
  }),
  rateLimit: defineTable({
    key: v.string(),
    count: v.number(),
    lastRequest: v.number(),
  })
    .index("key", ["key"]),
};


export default defineSchema({ ...baseTables,
  oauthClient: defineTable({
    clientId: v.string(),
    clientSecret: v.optional(v.union(v.null(), v.string())),
    disabled: v.optional(v.union(v.null(), v.boolean())),
    skipConsent: v.optional(v.union(v.null(), v.boolean())),
    enableEndSession: v.optional(v.union(v.null(), v.boolean())),
    subjectType: v.optional(v.union(v.null(), v.string())),
    scopes: v.optional(v.union(v.null(), v.array(v.string()))),
    userId: v.optional(v.union(v.null(), v.string())),
    createdAt: v.optional(v.union(v.null(), v.number())),
    updatedAt: v.optional(v.union(v.null(), v.number())),
    name: v.optional(v.union(v.null(), v.string())),
    uri: v.optional(v.union(v.null(), v.string())),
    icon: v.optional(v.union(v.null(), v.string())),
    contacts: v.optional(v.union(v.null(), v.array(v.string()))),
    tos: v.optional(v.union(v.null(), v.string())),
    policy: v.optional(v.union(v.null(), v.string())),
    softwareId: v.optional(v.union(v.null(), v.string())),
    softwareVersion: v.optional(v.union(v.null(), v.string())),
    softwareStatement: v.optional(v.union(v.null(), v.string())),
    redirectUris: v.array(v.string()),
    postLogoutRedirectUris: v.optional(v.union(v.null(), v.array(v.string()))),
    tokenEndpointAuthMethod: v.optional(v.union(v.null(), v.string())),
    grantTypes: v.optional(v.union(v.null(), v.array(v.string()))),
    responseTypes: v.optional(v.union(v.null(), v.array(v.string()))),
    public: v.optional(v.union(v.null(), v.boolean())),
    type: v.optional(v.union(v.null(), v.string())),
    requirePKCE: v.optional(v.union(v.null(), v.boolean())),
    referenceId: v.optional(v.union(v.null(), v.string())),
    metadata: v.optional(v.union(v.null(), v.any())),
  }).index("clientId", ["clientId"])
    .index("clientSecret", ["clientSecret"])
    .index("disabled", ["disabled"])
    .index("skipConsent", ["skipConsent"])
    .index("enableEndSession", ["enableEndSession"])
    .index("subjectType", ["subjectType"])
    .index("scopes", ["scopes"])
    .index("userId", ["userId"])
    .index("createdAt", ["createdAt"])
    .index("updatedAt", ["updatedAt"])
    .index("name", ["name"])
    .index("uri", ["uri"])
    .index("icon", ["icon"])
    .index("contacts", ["contacts"])
    .index("tos", ["tos"])
    .index("policy", ["policy"])
    .index("softwareId", ["softwareId"])
    .index("softwareVersion", ["softwareVersion"])
    .index("softwareStatement", ["softwareStatement"])
    .index("redirectUris", ["redirectUris"])
    .index("postLogoutRedirectUris", ["postLogoutRedirectUris"])
    .index("tokenEndpointAuthMethod", ["tokenEndpointAuthMethod"])
    .index("grantTypes", ["grantTypes"])
    .index("responseTypes", ["responseTypes"])
    .index("public", ["public"])
    .index("type", ["type"])
    .index("requirePKCE", ["requirePKCE"])
    .index("referenceId", ["referenceId"])
    .index("metadata", ["metadata"]),
  oauthRefreshToken: defineTable({
    token: v.string(),
    clientId: v.string(),
    sessionId: v.optional(v.union(v.null(), v.string())),
    userId: v.string(),
    referenceId: v.optional(v.union(v.null(), v.string())),
    expiresAt: v.number(),
    createdAt: v.number(),
    revoked: v.optional(v.union(v.null(), v.number())),
    authTime: v.optional(v.union(v.null(), v.number())),
    scopes: v.array(v.string()),
  }).index("token", ["token"])
    .index("clientId", ["clientId"])
    .index("sessionId", ["sessionId"])
    .index("userId", ["userId"])
    .index("referenceId", ["referenceId"])
    .index("expiresAt", ["expiresAt"])
    .index("createdAt", ["createdAt"])
    .index("revoked", ["revoked"])
    .index("authTime", ["authTime"])
    .index("scopes", ["scopes"])
    .index("clientId_userId", ["clientId", "userId"]),
  oauthAccessToken: defineTable({
    token: v.string(),
    clientId: v.string(),
    sessionId: v.optional(v.union(v.null(), v.string())),
    userId: v.optional(v.union(v.null(), v.string())),
    referenceId: v.optional(v.union(v.null(), v.string())),
    refreshId: v.optional(v.union(v.null(), v.string())),
    expiresAt: v.number(),
    createdAt: v.number(),
    scopes: v.array(v.string()),
  }).index("token", ["token"])
    .index("clientId", ["clientId"])
    .index("sessionId", ["sessionId"])
    .index("userId", ["userId"])
    .index("referenceId", ["referenceId"])
    .index("refreshId", ["refreshId"])
    .index("expiresAt", ["expiresAt"])
    .index("createdAt", ["createdAt"])
    .index("scopes", ["scopes"]),
  oauthConsent: defineTable({
    clientId: v.string(),
    userId: v.optional(v.union(v.null(), v.string())),
    referenceId: v.optional(v.union(v.null(), v.string())),
    scopes: v.array(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("clientId", ["clientId"])
    .index("userId", ["userId"])
    .index("referenceId", ["referenceId"])
    .index("scopes", ["scopes"])
    .index("createdAt", ["createdAt"])
    .index("updatedAt", ["updatedAt"])
    .index("clientId_userId", ["clientId", "userId"]),
});
