import type { DocSection } from "./types";

/** English docs. Keep slugs and heading ids identical to content-ar.ts. */
export const sectionsEn: DocSection[] = [
  {
    id: "getting-started",
    title: "Getting started",
    articles: [
      {
        slug: "first-form",
        title: "Make your first form",
        summary: "From a blank page to a link you can send, in a few minutes.",
        blocks: [
          { type: "p", text: "A form is a set of questions with a link. You build it in the builder, publish it, and send the link. Answers appear in Results." },
          { type: "heading", id: "create", text: "Create it" },
          {
            type: "steps",
            items: [
              "Sign in and open your **Library**.",
              "Press **New**. A blank draft opens in the builder. The small arrow next to **New** also offers **From a template** and **Import**.",
              "Click the title at the top and type a name. It reads \"Untitled form\" until you do.",
              "Under **Questions**, press a question type such as **Short text** or **Single choice**, then type your question.",
              "Add more questions the same way. Press **More types** to see every type.",
            ],
          },
          { type: "tip", text: "Changes save on their own. The label near the top tells you when they are saved. You do not need a Save button." },
          { type: "heading", id: "look", text: "Choose how it looks" },
          {
            type: "steps",
            items: [
              "Open the **Design** tab.",
              "Pick a theme. New forms start with **Google Forms style**, a look that resembles Google Forms.",
              "Pick a **Mode**: everything on one page, or one question at a time. See [Ways to answer](/docs/answer-modes).",
            ],
          },
          { type: "heading", id: "publish", text: "Publish and share" },
          {
            type: "steps",
            items: [
              "Press **Preview** to try the form yourself. Nothing you enter is saved.",
              "Press **Publish**. If something is missing, Chaos lists what to fix first.",
              "Open the **Share** tab, press **Copy** next to **Public link**, and send it.",
              "Open **Results** in the top bar to read answers as they arrive.",
            ],
          },
          { type: "p", text: "More on each step: [Question types](/docs/question-types), [Publish a form](/docs/publish), [Results](/docs/results)." },
        ],
      },
      {
        slug: "first-quiz",
        title: "Make a quiz",
        summary: "A quiz is a form with Quiz mode switched on.",
        blocks: [
          { type: "p", text: "Chaos has one kind of thing to make. A quiz is a form with the **Quiz mode** switch turned on. You can switch it on or off at any time." },
          {
            type: "steps",
            items: [
              "Press **New** in your Library.",
              "Turn on **Quiz mode**, under the title.",
              "Add questions of type **Single choice**, **Dropdown** or **Checkboxes**. Only these three can be marked right or wrong.",
              "Open a question. In the **Correct answer** box, choose the right option. For **Checkboxes**, tick every right option.",
              "Open **Points and explanation** to change the points (the default is 1) and add a short explanation people see after they answer.",
              "Publish and send the link.",
            ],
          },
          { type: "tip", text: "Correct answers stay on the server. People who open the quiz cannot see the answer key, even in their browser tools." },
          { type: "p", text: "Questions of other types, such as short text, are collected but not scored. See [Quizzes and scores](/docs/quizzes-and-scores) for how marks are added up." },
        ],
      },
      {
        slug: "around-the-workspace",
        title: "Find your way around",
        summary: "The sidebar, search, and the top bar.",
        blocks: [
          { type: "p", text: "After you sign in, everything happens in the workspace. The sidebar is at the side of the page." },
          { type: "heading", id: "sidebar", text: "The sidebar" },
          {
            type: "list",
            items: [
              "**Search** opens the command palette. It finds your forms and quizzes and runs actions such as New and Settings.",
              "**New** makes a blank draft.",
              "**Library** lists everything you made.",
              "**Pinned** and **Recent** show the forms you use most. See [Sidebar and pins](/docs/sidebar-and-pins).",
              "At the bottom: **Archive**, **Connections**, **Settings**, **Docs** and your account.",
            ],
          },
          { type: "heading", id: "phone", text: "On a phone" },
          { type: "p", text: "The sidebar becomes a menu. Press the menu button in the top corner. Press a page to go there and the menu closes." },
          { type: "heading", id: "topbar", text: "The top bar" },
          { type: "p", text: "It shows where you are, the notification bell for new responses and approvals, and a light or dark switch." },
          { type: "tip", text: "Press Ctrl+K (⌘+K on a Mac) anywhere in the workspace to search. Press Ctrl+B to hide or show the sidebar." },
        ],
      },
    ],
  },
  {
    id: "building",
    title: "Building",
    articles: [
      {
        slug: "question-types",
        title: "Question types",
        summary: "The 18 kinds of question, and how to add, order and change them.",
        blocks: [
          { type: "p", text: "Questions are on the **Questions** tab of the builder. Each one is a card. Click a card to open it." },
          { type: "heading", id: "add", text: "Add a question" },
          {
            type: "steps",
            items: [
              "Scroll to **Add a question** at the bottom.",
              "Press a type. The six most used are shown: **Short text**, **Long text**, **Single choice**, **Checkboxes**, **Rating** and **Email**.",
              "Press **More types** for the rest.",
              "To add one in the middle, hover between two questions and press **Insert here**.",
            ],
          },
          { type: "heading", id: "types", text: "All types" },
          {
            type: "list",
            items: [
              "**Short text** and **Long text**: a line or a paragraph. You can set a minimum and maximum length and a placeholder.",
              "**Email**, **Phone**, **Website**: text that is checked for the right shape. Chaos doesn't verify email addresses: an answer only has to look like an email, and Chaos does not check that it exists or belongs to the person.",
              "**Number**: with an optional minimum, maximum and step, and a **Whole numbers only** option. Numbers are stored as plain numbers with a dot for decimals, whatever language the person types in, and text that is not a number is refused, never turned into 0.",
              "**Date** and **Time**: with an optional earliest and latest. A date is saved exactly as picked (YYYY-MM-DD) and a time as HH:mm. No time zone conversion is applied.",
              "**Single choice**: pick one option. **Dropdown**: pick one from a menu. **Checkboxes**: pick any number, with an optional minimum and maximum.",
              "**Rating**: 3 to 10 stars. On an optional rating, **Clear answer** removes a rating that was chosen.",
              "**Linear scale**: from 0 or 1 up to 2 to 10, with an optional step and labels for the low and high ends. The labels show in the form, in each response, in the results **Summary** and in the export column heading.",
              "**Ranking**: people put options in order.",
              "**Likert / matrix**: rows of statements, columns of choices.",
              "**File upload**: 1 to 5 files. PDF, images, text, CSV, Word and Excel, up to 10 MB each. See [File uploads](/docs/file-uploads).",
              "**Text block**: a heading and text, with no answer. Use it for instructions.",
              "**Section break**: starts a new section with its own title.",
            ],
          },
          { type: "heading", id: "options", text: "Options" },
          { type: "p", text: "For choice, dropdown, checkbox and ranking questions, type each option in its own field. Press **Add an option** for another. Use the arrows to move one, and the cross to remove it. You can also edit all options as text, one per line." },
          { type: "heading", id: "edit", text: "Edit a question" },
          {
            type: "list",
            items: [
              "Turn on **Required** at the bottom of the card. A red star then shows next to the question.",
              "Press **Add a description** for help text under the question.",
              "Open **More options** to change the question type without losing the text, set limits, give options scores, or add an image with a description for people who cannot see it.",
              "Press the **…** button on the card to **Move up**, **Move down**, **Duplicate** or **Delete**.",
            ],
          },
          { type: "heading", id: "many", text: "Work on several at once" },
          { type: "p", text: "Hover a question and tick its box. A bar appears with **Required**, **Optional**, **Duplicate**, **Move to end** and **Delete** for every ticked question. **Clear** removes the ticks." },
          { type: "heading", id: "piping", text: "Use an earlier answer" },
          { type: "p", text: "Inside any question, description or ending, write `{{question-id}}` to insert what the person answered before. The id of a question is shown in its **More options**. Write `{{score}}` for the calculated score." },
          { type: "heading", id: "intro", text: "Introduction" },
          { type: "p", text: "The box at the top of the Questions tab is the introduction. Say why you are asking and how long it takes." },
          { type: "tip", text: "If a question cannot be published as it is, a line near the top says how many things to fix. Open it to see them." },
        ],
      },
      {
        slug: "file-uploads",
        title: "File uploads",
        summary: "Let people attach files to their answer, and what happens to those files.",
        blocks: [
          { type: "p", text: "A **File upload** question lets people attach documents or pictures, for example a CV or a photo of a receipt." },
          { type: "heading", id: "add", text: "Add a file question" },
          {
            type: "steps",
            items: [
              "Under **Add a question**, press **More types**, then **File upload**.",
              "Open **More options** and set **Files allowed**, from 1 to 5.",
              "Turn on **Required** if every response needs a file.",
            ],
          },
          { type: "heading", id: "limits", text: "What people can upload" },
          {
            type: "list",
            items: [
              "PDF, PNG, JPEG, WebP and GIF images, plain text, CSV, Word (.docx) and Excel (.xlsx).",
              "Up to 10 MB per file. Empty files are refused.",
              "Uploads only work while the form is live and open. A closed, full or scheduled form refuses them.",
            ],
          },
          { type: "heading", id: "who", text: "Who can open the files" },
          { type: "p", text: "Files show inside the response in [Results](/docs/results), for you and your collaborators. Press a file to download it. A download link opens the file for whoever has it, so share it with the same care as the file." },
          { type: "p", text: "Files are not sent to connected apps, and the integration API and the ChatGPT app cannot add file questions." },
          { type: "heading", id: "exports", text: "Files in exports" },
          { type: "p", text: "Excel, CSV and JSON exports show how many files a person sent, for example `2 files`. The files themselves are not in the export. Open a response to download them. See [Export responses](/docs/export-responses)." },
          { type: "heading", id: "deleting", text: "When files are deleted" },
          {
            type: "list",
            items: [
              "A file uploaded by someone who never sends the form is removed after about a day.",
              "Deleting a response, deleting a form, or **Delete responses after** in [privacy settings](/docs/access-and-limits#privacy) removes its files too.",
            ],
          },
          { type: "tip", text: "Ask only for the files you need. If they hold personal data, set **Delete responses after** so they are not kept longer than necessary." },
        ],
      },
      {
        slug: "logic",
        title: "Logic and branching",
        summary: "Show a question or section only when an earlier answer calls for it.",
        blocks: [
          { type: "p", text: "Branching hides questions that do not apply. A hidden question is skipped, and nothing is stored for it." },
          { type: "heading", id: "add-rule", text: "Add a condition" },
          {
            type: "steps",
            items: [
              "Open a question that is not the first one.",
              "Press **Logic** at the bottom of the card.",
              "Press **Add condition**. Choose an earlier question, how to compare, and the answer to compare with.",
              "Add more conditions if you need them. When there are two or more, choose whether **all** or **any** must be true.",
            ],
          },
          { type: "p", text: "A question with a condition shows a small branch icon in the list. The same works on a **Section break** to show or hide a whole section." },
          { type: "heading", id: "compare", text: "What you can compare" },
          {
            type: "list",
            items: [
              "Choices: **is**, **is not**, **is answered**, **is not answered**. Checkboxes also have **includes** and **does not include**.",
              "Numbers, ratings and scales: **is**, **is not**, **is greater than**, **is at least**, **is less than**, **is at most**.",
              "Any other question: **is answered** or **is not answered**.",
              "The **Calculated score**, if any option has a score. Give scores in **More options** of a choice question.",
            ],
          },
          { type: "p", text: "A condition can only look at questions above it. Matrix and file questions cannot be used." },
          { type: "heading", id: "test", text: "Test your logic" },
          { type: "p", text: "Open **More**, then **Logic and endings**. On the right, **Test your logic** works like the real form. Answer it and watch the score, the ending, and a reason for each question being shown or hidden. Nothing is saved. Press **Reset** to start again." },
          { type: "tip", text: "If a rule points at a question you delete, Chaos removes that condition and tells you." },
        ],
      },
      {
        slug: "endings",
        title: "Endings",
        summary: "The message people see after they submit.",
        blocks: [
          { type: "p", text: "Without any ending, people see a standard thank-you message. Add your own under **More**, then **Logic and endings**." },
          {
            type: "steps",
            items: [
              "Press **Add ending**.",
              "Type a **Title** and a **Message**.",
              "To show it only to some people, add a condition under **Show this ending if**, for example the calculated score is at least 8.",
              "Add more endings for other cases. Use **Move up** to change the order.",
            ],
          },
          { type: "p", text: "People see the first ending whose conditions match. If none match, they see the first ending that has no conditions." },
          { type: "p", text: "Write `{{score}}` or `{{question-id}}` in the title or message to show results." },
        ],
      },
      {
        slug: "quizzes-and-scores",
        title: "Quizzes and scores",
        summary: "How marks work, and how to show a result.",
        blocks: [
          { type: "heading", id: "marking", text: "Marking" },
          { type: "p", text: "In Quiz mode, each **Single choice**, **Dropdown** and **Checkboxes** question has a **Correct answer** box. A question is worth the points you set, 1 by default. A person gets the points only for a fully correct answer. For **Checkboxes** that means exactly the right set, no more and no less." },
          { type: "p", text: "Hidden questions do not count. A person's score is the sum of what they earned, out of the points that were possible for them." },
          { type: "heading", id: "explain", text: "Explanations" },
          { type: "p", text: "Open **Points and explanation** on a question to add a short note. People see it after they submit." },
          { type: "heading", id: "result", text: "Show a result" },
          {
            type: "list",
            items: [
              "The ending screen shows the person's quiz score.",
              "In Results, each response shows its score.",
              "For a result such as \"Type A\" or \"Beginner\", give options scores in **More options**, then use endings that check the **Calculated score**.",
            ],
          },
          { type: "tip", text: "Turning Quiz mode off keeps your questions." },
          { type: "p", text: "Quizzes made in the old quiz editor stay as they are. They appear in your Library as **Old quiz** and open in the old editor." },
          { type: "heading", id: "old-quiz-rules", text: "How old quizzes are marked" },
          {
            type: "list",
            items: [
              "**Single choice and true or false:** the answer must match the correct one, ignoring capital letters and spaces at the ends. Otherwise 0.",
              "**Multiple select:** full points only when the chosen options are exactly the correct ones. One missing or one extra gives 0. Choosing the same option twice does not help.",
              "**Written answers:** each keyword you set must appear as a whole word or phrase. \"cat\" does not match \"concatenate\". Capital letters, extra spaces, Arabic diacritics and the letter forms أ إ آ ا, ى ي and ة ه are ignored, and so are attached Arabic prefixes like ال, وال, بال and لل, so \"مدرسة\" matches \"المدرسة\". A blank answer scores 0. All keywords found gives full points.",
              "**Half marks:** if not all keywords are found but the share found is at least **Half marks from** in [Settings](/dashboard/settings) (50% by default), the answer gets half the points, which can end in .5. Below that it gets 0.",
              "A question can be answered once per attempt, and only if it belongs to that quiz. A written question with no keywords gets full points.",
              "**Choices with commas:** an option such as \"Paris, France\" is marked correctly. **Keyboard and screen readers:** respondents can answer with the keyboard, and the Next question button moves to the next question. In the editor, use the up and down buttons on a question to reorder it. **Printing:** the print page has an **Include the answer key** box, off by default. Only the quiz owner can open the print page.",
            ],
          },
          { type: "tip", text: "Keyword marking checks words. It does not understand meaning, so a correct answer in different words can miss. List the words a good answer must contain, and review written answers yourself when it matters." },
          { type: "p", text: "New answers follow these rules. Answers already saved keep the marks they got." },
        ],
      },
    ],
  },
  {
    id: "design",
    title: "Design",
    articles: [
      {
        slug: "themes",
        title: "Themes",
        summary: "Pick a look, change it, and reset it.",
        blocks: [
          { type: "p", text: "A theme sets the colours, type and shape of what people see. It never changes what you see in Chaos. Open the **Design** tab to work on it. The preview beside it updates as you go." },
          { type: "heading", id: "choose", text: "Choose a theme" },
          { type: "p", text: "There are 18 themes. **Google Forms style** is the default. **Paper** is still there if you want the plainer card look. **Evergreen** is the bold green look Chaos started with. Others include **Soft grid**, **Spotlight**, **Terracotta**, **Ocean**, **Midnight**, **Garden**, **Neon**, **Aurora**, **Candy**, **Terminal**, **Newsprint**, **Arcade**, **Velvet** and **Sunset**." },
          { type: "steps", items: ["Open **Design**.", "Under **Theme**, press a tile.", "Check the preview. On a phone, press **Preview** for a full-screen view."] },
          { type: "heading", id: "look-alikes", text: "Google Forms and Microsoft Forms styles" },
          { type: "p", text: "**Google Forms style** has a lilac page, a white title card with a coloured strip on top, one card per question, underlined text boxes, round radio buttons and a **Submit** button on the left with **Clear form** on the right. Its type is Roboto, and Arabic text uses Cairo." },
          { type: "p", text: "**Microsoft Forms style** has a full-width coloured banner with the title, one white column below it, numbered questions and boxed inputs. It uses the Segoe UI font that comes with Windows. On other devices the system font shows instead, because Chaos does not include Segoe." },
          { type: "list", items: ["Change the **Accent** colour to recolour the strip, the banner, buttons and question numbers.", "Both styles show all questions on one page. In the other modes only the colours and fonts apply.", "They resemble those products. They are not affiliated with Google or Microsoft, and use no logos."] },
          { type: "heading", id: "reset", text: "Reset a theme" },
          { type: "p", text: "Once you change anything, the heading reads **Google Forms style · edited** (or whichever theme you started from) and a **Reset** button appears. It puts the colours, fonts, buttons and layout back. Your logo and your sound choice stay." },
          { type: "heading", id: "saved", text: "Save a theme for later" },
          { type: "p", text: "Open **Customize colours, fonts and more**, then **Saved themes**. Type a name and press **Save**. Apply it from the same list on any other form, or press the bin to delete it." },
          { type: "heading", id: "defaults", text: "The theme new forms start with" },
          { type: "p", text: "Open [Settings](/dashboard/settings), then **New forms**. Choose a theme, a mode, a language and whether sounds are on. Templates and imports keep their own look." },
          { type: "tip", text: "Every theme has a light and a dark version. People whose device is in dark mode get the dark one if you choose **Follow device** under Dark mode." },
        ],
      },
      {
        slug: "customize-design",
        title: "Colours, fonts and start screens",
        summary: "Everything under Customize on the Design tab.",
        blocks: [
          { type: "heading", id: "start-screen", text: "Start screen" },
          { type: "p", text: "The screen people see before the first question, with the title, your introduction and a start button. Choose **No start screen** to skip it, or one of **Centered**, **Split**, **Poster**, **Minimal**, **Editorial**, **Scroll**, **Terminal** or **Arcade**." },
          { type: "heading", id: "colours", text: "Colours" },
          { type: "p", text: "Open **Customize colours, fonts and more**. Under **Colours** you can set **Accent**, **Page**, **Surface** and **Text**. Press a swatch to pick a colour, or type a hex code such as `#3595e3`." },
          { type: "list", items: ["**Light** and **Dark** with the shuffle icon give a random palette that works.", "If two colours are hard to tell apart, a **Low contrast** note names the pair and its ratio. Fix it so everyone can read the form."] },
          { type: "heading", id: "dark", text: "Dark mode" },
          { type: "p", text: "**Always as designed** shows your colours to everyone. **Follow device** shows a dark version to people whose device is set to dark." },
          { type: "heading", id: "fonts", text: "Font" },
          { type: "p", text: "Choose **Modern**, **Grotesk**, **Serif**, **Editorial**, **Elegant**, **Rounded**, **Mono**, **Roboto** or **Segoe UI**. Arabic text uses Arabic fonts whichever you pick." },
          { type: "heading", id: "buttons", text: "Buttons and corners" },
          { type: "list", items: ["Buttons: **Solid**, **Soft**, **Rounded**, **Outline** or **Bold**.", "Corners: **Square**, **Soft** or **Round**.", "Page layout, for the all-on-one-page modes: **Open**, **Card** or **Spacious**."] },
          { type: "heading", id: "background", text: "Background" },
          { type: "p", text: "Plain, **Dots**, **Grid**, **Glow**, **Aurora**, **Grain**, **Stripes** or **Scanlines**." },
          { type: "heading", id: "logo", text: "Logo" },
          { type: "p", text: "Paste the address of an image that starts with `https://`. It shows on your form." },
          { type: "tip", text: "Changed too much? Press **Reset** next to the theme heading, or Ctrl+Z to undo one step at a time." },
        ],
      },
      {
        slug: "answer-modes",
        title: "Ways to answer",
        summary: "All on one page, section by section, one at a time, or swipe.",
        blocks: [
          { type: "p", text: "Under **Mode** on the Design tab you choose how people move through the form. You can change it at any time, even after you publish." },
          { type: "heading", id: "classic", text: "Classic" },
          { type: "p", text: "Every question on one scrolling page. It suits registrations and long surveys." },
          { type: "heading", id: "sections", text: "Sections" },
          { type: "p", text: "One page for each **Section break**. Good when a long form has clear parts." },
          { type: "heading", id: "one-at-a-time", text: "Typeform style" },
          { type: "p", text: "One question at a time. Each new question slides up. People press Enter to continue, or use the up and down arrows on screen." },
          {
            type: "keys",
            items: [
              { keys: ["Enter"], label: "Next question" },
              { keys: ["Ctrl", "Enter"], label: "Continue from a long text answer" },
              { keys: ["A", "B", "C"], label: "Choose an option by its letter" },
              { keys: ["1", "2", "3"], label: "Choose a rating or scale value" },
            ],
          },
          { type: "heading", id: "swipe", text: "Swipe" },
          { type: "p", text: "Full-screen cards. On a phone people swipe up to go on. On a computer the arrow keys and the buttons work. It suits short forms and quizzes on phones." },
          { type: "tip", text: "Use **Restart preview** on the Design tab to see the start screen and the first question again." },
        ],
      },
      {
        slug: "sounds",
        title: "Sounds",
        summary: "Optional taps and chimes for the people answering.",
        blocks: [
          { type: "p", text: "Sounds are part of a form or quiz, for the people who answer it. Chaos itself is silent. They play on things like choosing an option or finishing." },
          {
            type: "steps",
            items: [
              "Open the **Design** tab and find **Sounds**.",
              "Use the switch to turn sounds on or off.",
              "Press a pack to hear it: **Glass** (gentle chimes), **Pop** (bubbly), **Wood** (warm marimba) or **Arcade** (8-bit blips).",
            ],
          },
          { type: "p", text: "Each theme suggests a pack. Changing the theme does not switch sounds off. **Reset** keeps your sound choice." },
          { type: "p", text: "To choose whether new forms start with sounds, open [Settings](/dashboard/settings), then **New forms**, then **Sounds**." },
          { type: "tip", text: "Playing a pack in the builder is only a preview for you. It is the one place Chaos makes sound for the person building." },
        ],
      },
    ],
  },
  {
    id: "sharing",
    title: "Sharing",
    articles: [
      {
        slug: "publish",
        title: "Publish a form",
        summary: "Drafts, live forms, versions, and what each status means.",
        blocks: [
          { type: "p", text: "A new form is a **Draft**. Only you and your collaborators can open it. Press **Publish** to make it live." },
          { type: "heading", id: "publishing", text: "Publish" },
          {
            type: "steps",
            items: [
              "Press **Publish** in the top bar of the builder.",
              "If something blocks it, Chaos lists it. Fix these and press **Publish** again.",
              "When it works, the button reads **Published** and the **Share** tab shows your link.",
            ],
          },
          { type: "heading", id: "changes", text: "Changing a live form" },
          { type: "p", text: "Your edits save to the draft. People keep seeing the published version until you press **Publish changes**. Each publish makes a new numbered version, and each response stays with the version it answered." },
          { type: "heading", id: "status", text: "Status" },
          {
            type: "list",
            items: [
              "**Draft**: not published.",
              "**Live**: open for answers.",
              "**Closed**: still published but not taking answers. People see your closed message.",
              "**Archived**: hidden from your Library. See [Archive](/docs/archive).",
            ],
          },
          { type: "p", text: "Change the status under **Settings**, in the **Sharing** rows: **Close**, **Reopen** or **Restore**." },
          { type: "heading", id: "versions", text: "Earlier versions" },
          { type: "p", text: "Open **More**, then **History**. Pick a version to see its questions. **Copy into draft** brings it back as your draft. It does not go live until you publish." },
          { type: "heading", id: "approval", text: "When an editor needs approval" },
          { type: "p", text: "If the owner turned on **Editors need my approval to publish**, an editor presses **Request publication**. The owner is notified and presses **Approve & publish** or **Decline**." },
        ],
      },
      {
        slug: "links-and-embed",
        title: "Links and embedding",
        summary: "The public link, your own custom link, language links and embed code.",
        blocks: [
          { type: "heading", id: "link", text: "The public link" },
          { type: "p", text: "Every published form has a link like `chaos.fail/f/abc123`. Open the **Share** tab and press **Copy**. You can also press the **…** in the builder header, then **Copy link**, or use the link menu on a card in your Library." },
          { type: "heading", id: "custom-links", text: "A custom link" },
          { type: "p", text: "A custom link looks like `chaos.fail/yourname/team-lunch`. The first part is your username. The second is a name you pick for this form." },
          {
            type: "steps",
            items: [
              "Open **Settings** in the builder, in the **Sharing** rows.",
              "Turn on **Custom link**.",
              "The first time, choose a username: 3 to 30 letters, numbers, dots, dashes or underscores.",
              "Type the link name and press **Save link**.",
            ],
          },
          { type: "p", text: "The old `/f/` link keeps working. Change the link name any time with **Change**. Turn the switch off to remove the custom link. Changing your username in [Settings](/dashboard/settings) moves every custom link with you." },
          { type: "heading", id: "language-links", text: "Open in a language" },
          { type: "p", text: "Add `?lang=ar` for Arabic or `?lang=en` for English at the end of the link. The form must have that language turned on. See [Languages](/docs/languages)." },
          { type: "heading", id: "embed", text: "Embed on a website" },
          { type: "p", text: "You can show a published form inside a page on your own site. Embedding is off for every form until you turn it on, and only the sites you list can show the form." },
          {
            type: "steps",
            items: [
              "Publish the form. Drafts can never be embedded.",
              "Open the **Share** tab and find **Embed on a website**.",
              "Turn on **Allow embedding**.",
              "Under **Sites allowed to embed**, type each site on its own line, like `https://example.com`. Use `https://*.example.com` for every subdomain. You can add up to 20.",
              "Press **Save**, then press **Copy** next to the **Embed code** and paste it into your page.",
            ],
          },
          { type: "p", text: "The code is an iframe plus a short script that resizes the frame to fit the form. If your site does not allow scripts, clear **Resize to fit the form** and copy the iframe on its own. The **Live preview** under the code is the real form: answers sent there count as responses." },
          { type: "tip", text: "**Any site** lets every website show the form. It suits a public form anyone may answer. People answer anonymously, and nobody is signed in to Chaos inside the frame." },
          {
            type: "list",
            items: [
              "Forms that ask respondents to sign in cannot be embedded. Choose **Anyone** or **With a code** under **Who can respond**.",
              "Your dashboard, the admin area and every other Chaos page always refuse to open inside another site.",
              "Owners and editors can change embedding. Viewers can only see it.",
            ],
          },
          { type: "heading", id: "domain", text: "Your own domain" },
          { type: "p", text: "Custom domains are not available yet. Use the link or the embed code on your own site." },
          { type: "heading", id: "qr-code", text: "QR code" },
          { type: "steps", items: ["Open the **Share** tab of a published form.", "Under **QR code**, press **Download PNG** for print or **Download SVG** for any size.", "Press **Show large** to put the code full screen, for example on a projector. Press Esc to close it."] },
          { type: "tip", text: "The code opens the link shown next to it. Drafts have no QR code until you publish." },
        ],
      },
      {
        slug: "live-games",
        title: "Live games",
        summary: "Play a quiz together: questions on a big screen, answers on phones, a leaderboard after each one.",
        blocks: [
          { type: "p", text: "A live game runs a quiz for a room. You show the questions on a projector or shared screen. Players join on their phones with a PIN, tap a coloured shape to answer, and see if they were right. Faster correct answers earn more points." },
          { type: "heading", id: "start", text: "Start a game" },
          {
            type: "steps",
            items: [
              "Open **Games** and press **Create a game**. Write choice questions with 2–4 options, mark the right answers and **Publish**.",
              "Press **Host live**. Put the host screen on a projector.",
              "Players open `chaos.fail/play` and type the PIN, or scan the QR code. No account needed.",
              "Press **Start**. A 5-4-3-2-1 countdown plays, then the first question.",
            ],
          },
          { type: "tip", text: "Only choice questions with 2–4 options and a right answer are played. The host screen says how many were skipped." },
          { type: "heading", id: "play", text: "During the game" },
          {
            type: "list",
            items: [
              "**Autoplay is on by default.** Each question ends when time runs out or everyone has answered. The answer shows, then the leaderboard, then the next question starts.",
              "Press **Pause** to stay on a screen, and **Autoplay** to carry on. **Next** skips ahead at any time.",
              "After the last question, the podium shows the top 3 and everyone's answers are saved to Results.",
            ],
          },
          { type: "heading", id: "settings", text: "Game settings" },
          {
            type: "list",
            items: [
              "**Time per question**: 5 to 240 seconds.",
              "**Autoplay** and **Pause between questions**: how long the answer and leaderboard stay up (3–20 seconds). Turn autoplay off to press Next yourself.",
              "**Start when this many join**: the countdown starts by itself once that many players are in.",
              "**Theme** and **Show answer text on phones**.",
              "Sound is on. Anyone can mute their own device with the speaker button.",
            ],
          },
          { type: "heading", id: "points", text: "Points" },
          {
            type: "list",
            items: [
              "A correct answer earns 500 to 1000 points: 1000 at once, down to 500 at the last second. A wrong answer earns 0.",
              "Three or more correct answers in a row earn a bonus: +100 for the third, +200 for the fourth, up to +500.",
              "Right or wrong is decided exactly as in a normal quiz. The Chaos server keeps the time, so a late answer is not counted, whatever the phone's clock says.",
            ],
          },
          { type: "heading", id: "players", text: "Players and safety" },
          {
            type: "list",
            items: [
              "Nicknames can have up to 20 letters, numbers and spaces. Rude names are refused, and two players can't share a name.",
              "Press the **×** next to a name in the lobby to remove a player. They can't answer or rejoin with that device.",
              "A game holds up to 100 players on Free.",
              "If a phone sleeps or loses its connection, the player returns to the game by opening `chaos.fail/play` again on the same device.",
              "A game that nobody moves on for three hours ends by itself.",
            ],
          },
          { type: "heading", id: "results", text: "Results" },
          { type: "p", text: "When the game ends, each player's answers are saved as a response in [Results](/docs/results), with their nickname and the tag **live**, so export and webhooks include them. For an old quiz they appear in its results. Players who answered nothing are not saved." },
          { type: "heading", id: "accessibility", text: "Sound, motion and screen readers" },
          {
            type: "list",
            items: [
              "Sounds follow the quiz's theme. Press the speaker in the top bar to mute; silent themes have no speaker control. Phones vibrate where supported.",
              "If a device asks for reduced motion, the game shows no animation or confetti.",
              "Everything works with a keyboard. On a phone or computer, keys 1 to 4 choose an answer. Screen readers hear the question, the time left at 10 and 5 seconds, and the result.",
            ],
          },
        ],
      },
      {
        slug: "access-and-limits",
        title: "Who can respond, and limits",
        summary: "Access codes, sign-in, response limits, open and close dates.",
        blocks: [
          { type: "p", text: "These are in the builder under **Settings**. Press **Save** in the bar that appears when you change something, or **Discard** to go back." },
          { type: "heading", id: "who", text: "Who can respond" },
          {
            type: "list",
            items: [
              "**Anyone**: anyone with the link. Answers are anonymous, so Chaos cannot limit one person to one response.",
              "**Signed in**: people signed in to Chaos. Their responses are linked to their account. Turn on **One response per person** if you need it.",
              "**With a code**: people you give an access code to, for example invited guests. Type a code of at least 6 characters. After 20 wrong tries in 10 minutes the form stops accepting codes for a few minutes. When you edit a form that already has a code, leave the box empty to keep it.",
            ],
          },
          { type: "heading", id: "limits", text: "Limits" },
          {
            type: "list",
            items: [
              "**Response limit**: after this many responses the form says it is full. Nothing is deleted.",
              "**Opens**: the date and time it starts accepting answers. Before that, people see when it opens.",
              "**Time zone**: the zone the opening and closing times are read in. It starts as your browser's zone and is saved with the schedule. Schedules saved before this existed keep working: they open and close at the same moment, shown in your browser's zone until you save.",
              "**Closes**: the date and time it stops. Respondents see the time with its zone. Daylight saving changes are handled for you: a time that does not exist because clocks jump forward means the moment just after the jump, and a time that happens twice means the first one.",
              "Press the cross next to a date to clear it.",
              "The server decides, not the browser. A form that is not live never opens, whatever the schedule. Someone who started before the closing time cannot send answers after it, and sees that the form has closed.",
            ],
          },
          { type: "p", text: "Limits you set show under the form title in the builder, for example **Closes 4 Oct, 18:00** or **12 of 50 responses**." },
          { type: "heading", id: "close", text: "Close and reopen" },
          { type: "p", text: "At the top of **Settings**, press **Close** to stop answers now. Press **Reopen** to accept them again. Undo is offered right after." },
          { type: "heading", id: "closed-message", text: "Message when closed or full" },
          { type: "p", text: "Open **More settings** and write what people should see, for example where to ask for a new link." },
          { type: "heading", id: "privacy", text: "Privacy settings" },
          {
            type: "list",
            items: [
              "**Delete responses after**: a number of days. Responses and their files are removed after that time. Leave empty to keep them.",
              "**Show in search engines**: lets the form be found by search.",
              "Deleting a form removes its responses too.",
            ],
          },
          { type: "heading", id: "notifications", text: "Notifications" },
          { type: "p", text: "Under **More settings**, **Notifications and team**, turn on **Every new response** to get a notification for each one. **Add a rule** under **Responses that match** to be told only about some answers, for example when a rating is at most 2. Notifications appear under the bell in the top bar." },
        ],
      },
      {
        slug: "respondent-experience",
        title: "What people see when they answer",
        summary: "Saving, receipts, editing, and continuing later.",
        blocks: [
          { type: "p", text: "You choose most of this under **Settings**, then **More settings**, then **Responses**." },
          { type: "heading", id: "saved", text: "Saved on their device" },
          { type: "p", text: "Answers are kept on the person's device until they submit. If they close the page and come back, the form restores them and offers **Start over**." },
          { type: "heading", id: "resume", text: "Continue on another device" },
          { type: "p", text: "When this is on, a person can get a private link that holds their answers for 30 days. Anyone with the link can see and continue them. You cannot see these unfinished copies." },
          { type: "heading", id: "partial", text: "Collect unfinished responses" },
          { type: "p", text: "Turn this on to see answers from people who left before submitting. People are told you can see them. It also lets the results **Summary** show where people stop. See [Unfinished responses](/docs/partial-responses)." },
          { type: "heading", id: "edit-later", text: "Edit after submitting" },
          { type: "p", text: "When on, the receipt includes a private link to change the answers. It is off by default. Anonymous people cannot be identified, so the private link is the only proof: anyone who holds it can edit that response, and nobody can edit without it." },
          { type: "p", text: "An edit never overwrites the original. Chaos keeps every earlier version. Open a response and choose **Earlier versions** to read them. Results and exports show the latest version, and mark responses that were edited." },
          { type: "p", text: "Turn on **Allow edits after closing** if edit links should keep working after the closing time, after you close the form, or when it is full. New responses stay closed. Earlier versions are deleted with the response and with the form." },
          { type: "heading", id: "receipt", text: "Receipt code" },
          { type: "p", text: "After submitting, people see a receipt code and can save it as a file. The same code appears next to the response in your Results." },
          { type: "heading", id: "language", text: "Language" },
          { type: "p", text: "If a form has more than one language, people see a switch and can change at any time. See [Languages](/docs/languages)." },
        ],
      },
      {
        slug: "team",
        title: "Collaborators and comments",
        summary: "Invite editors and viewers, and leave notes.",
        blocks: [
          { type: "p", text: "Open **More**, then **Team** in the builder." },
          { type: "heading", id: "invite", text: "Invite someone" },
          {
            type: "steps",
            items: [
              "Type their email and choose **Editor** or **Viewer**.",
              "Press **Invite**.",
              "Tell them yourself. Chaos does not send an invitation email. They get access when they sign in with that email.",
            ],
          },
          {
            type: "list",
            items: [
              "**Editors** change the draft and can publish, or request publication if you turned on approval.",
              "**Viewers** read the form and its responses.",
              "Only the owner changes settings, links and access, or deletes the form.",
            ],
          },
          { type: "p", text: "Change a person's role with **Make editor** or **Make viewer**, or press the bin to remove them." },
          { type: "heading", id: "comments", text: "Comments" },
          { type: "p", text: "Write a note for collaborators. Pick a question in the list to attach it, or leave **Whole form**. Press **Resolve** when it is dealt with. **Show resolved** brings resolved notes back." },
          { type: "heading", id: "activity", text: "Activity" },
          { type: "p", text: "A list of who changed what, and when." },
          { type: "heading", id: "shared", text: "Forms shared with you" },
          { type: "p", text: "They appear in your Library under **Shared with you**." },
        ],
      },
    ],
  },
  {
    id: "results",
    title: "Results",
    articles: [
      {
        slug: "results",
        title: "Read your results",
        summary: "The summary, individual responses and how to sort through them.",
        blocks: [
          { type: "p", text: "Press **Results** in the builder header, or **Results** in the **…** menu of a form in your Library. The top shows the numbers at a glance: responses, completion rate, average time, the last response and a small chart of the last 30 days. Quiz forms add the average and median score and how many scored 50% or more. Below are three tabs: **Summary**, **Responses** and **Export**." },
          { type: "heading", id: "analysis", text: "Summary" },
          {
            type: "list",
            items: [
              "One card per question, with how many answered and how many skipped.",
              "Choices, dropdowns, checkboxes, ratings and scales show a bar per option with its count and share.",
              "Numbers show the lowest, average, median and highest, with a chart of how answers spread. Dates show the earliest and latest.",
              "Written answers are listed newest first, with a search box.",
              "In a quiz, each question shows the share of correct answers, the correct answer and the most common wrong answer.",
              "Where unfinished people stopped, if you collect unfinished responses, and the endings and languages people reached.",
            ],
          },
          { type: "heading", id: "responses", text: "Responses" },
          { type: "p", text: "Each response is a row with its time, first answers, score and status. Press one to read it beside the list (or as a sheet on a phone), with its receipt code, time taken, language, version and, for signed-in forms, who answered. Use **↑** and **↓** to move through the list and **Enter** to open a response; inside it, the arrow buttons step to the previous and next one." },
          {
            type: "list",
            items: [
              "**Search answers** looks inside answers as you type.",
              "The **Status**, **Reviewed**, **Tag** and **Folder** buttons filter the list. **Sort** switches between newest and oldest first.",
              "**Views** saves the current filters and search, and brings them back later.",
              "In a response: **Reviewed**, add or remove tags, **Print** just that response, or delete it.",
              "Tick responses to mark them reviewed, tag them, move them to spam or delete them together.",
            ],
          },
          { type: "tip", text: "Responses that were submitted very fast or that filled a hidden field go to the **Spam** folder and are kept out of totals until you press **Not spam**." },
          { type: "heading", id: "deleting", text: "Deleting responses" },
          { type: "p", text: "Responses can be deleted with their files after you confirm. This cannot be undone. Only the form's owner can do it." },
        ],
      },
      {
        slug: "partial-responses",
        title: "Unfinished responses",
        summary: "What collecting unfinished answers stores, when it saves, and what it means for privacy.",
        blocks: [
          { type: "p", text: "Normally Chaos stores nothing until a person presses submit. With **Collect unfinished responses** on, Chaos also keeps the answers of people who start but do not finish. It is off for every new form." },
          { type: "heading", id: "turn-on", text: "Turn it on" },
          { type: "steps", items: ["In the builder, open **Settings**, then **More settings**, then **Responses**.", "Turn on **Collect unfinished responses** and press **Save**."] },
          { type: "heading", id: "when", text: "When answers are saved" },
          {
            type: "list",
            items: [
              "A few seconds after a person answers or changes a question, their answers so far are saved as an unfinished response.",
              "When they submit, the same response becomes a finished one. Nothing is counted twice.",
              "If they never submit, it stays unfinished until you delete it or your **Delete responses after** period removes it.",
            ],
          },
          { type: "heading", id: "privacy", text: "Privacy" },
          {
            type: "list",
            items: [
              "People see a note on the form saying that you can see unfinished answers.",
              "Unfinished answers can hold things a person typed and then chose not to send. Only turn this on when you need it, and say why in your introduction.",
              "They are separate from **Continue on another device**: those private copies are never visible to you.",
              "Unfinished responses do not trigger webhooks, notifications or response counts, and connected apps never see them.",
            ],
          },
          { type: "heading", id: "where", text: "Where you see them" },
          { type: "p", text: "In [Results](/docs/results), filter **Status** to see them. The **Summary** shows where people stopped. Exports leave them out unless you turn on **Include unfinished responses**. See [Export responses](/docs/export-responses)." },
        ],
      },
      {
        slug: "export-responses",
        title: "Export responses",
        summary: "Excel, CSV and JSON files, and a file of the form itself.",
        blocks: [
          { type: "heading", id: "responses", text: "Export responses" },
          { type: "steps", items: ["Open **Results**, then the **Export** tab.", "Turn on **Include unfinished responses** or **Include responses flagged as spam** if you want them.", "Press **Download** next to **Excel (.xlsx)**, **CSV** or **JSON**."] },
          {
            type: "list",
            items: [
              "Spreadsheets have one column per question, and a few extra: response ID, receipt, status, time, language, seconds, version, ending, quiz score, tags, reviewed, edited and last edited. Edited responses show their latest answers.",
              "For matrix questions there is one column per row.",
              "**JSON** keeps the raw answers with stable option identifiers.",
              "File upload answers show how many files were sent. Open a response to download the files. See [File uploads](/docs/file-uploads#exports).",
            ],
          },
          { type: "tip", text: "Exports contain everything you can see, including names and emails for signed-in forms. Store the file with care." },
          { type: "heading", id: "form-file", text: "Export the form" },
          { type: "p", text: "On the **Share** tab, **Download form file** saves the questions, logic, translations and design. It never includes responses or access codes. You can import it into any Chaos account. See [Templates and import](/docs/templates-and-import)." },
        ],
      },
    ],
  },
  {
    id: "library",
    title: "Library and organizing",
    articles: [
      {
        slug: "library",
        title: "Your Library",
        summary: "Search, filter, sort and group your forms and quizzes.",
        blocks: [
          { type: "p", text: "The Library lists every form and quiz you own, plus those shared with you." },
          { type: "heading", id: "find", text: "Find things" },
          {
            type: "list",
            items: [
              "The tabs **All**, **Forms** and **Quizzes** narrow the list.",
              "**Search** filters by title as you type.",
              "**Status** filters by **Live**, **Draft** or **Closed**. You can choose more than one.",
            ],
          },
          { type: "heading", id: "views", text: "Gallery or list" },
          { type: "p", text: "Open **View options** to switch between **Gallery**, with thumbnails, and **List**, a table. The choice is remembered." },
          { type: "heading", id: "sort", text: "Sort" },
          { type: "p", text: "In the list, click a column name: **Name**, **Status**, **Responses** or **Edited**. Click it again to reverse the order. In the gallery, use the **Sort** menu. You can also set a default in [Settings](/dashboard/settings)." },
          { type: "heading", id: "folders", text: "Folders" },
          { type: "p", text: "Under **More settings**, **Notifications and team**, the **Folder** row puts a form in a named group. The Library shows the groups as headings. Forms shared with you are grouped as **Shared with you**." },
          { type: "heading", id: "menu", text: "The … menu on a form" },
          { type: "p", text: "**Open**, **Results**, **View live**, **Copy link**, **Pin to sidebar**, **Duplicate** and **Archive**. There is no Delete here. See [Archive](/docs/archive)." },
        ],
      },
      {
        slug: "sidebar-and-pins",
        title: "Sidebar and pins",
        summary: "Pin favourites, fold sections, hide or resize the sidebar.",
        blocks: [
          { type: "heading", id: "pin", text: "Pin a form" },
          { type: "p", text: "Hover a form in the sidebar and press the pin icon. Or use **Pin to sidebar** in the **…** menu in the Library, or the builder header. Pinned forms appear under **Pinned**. Pins are saved on this device." },
          { type: "heading", id: "sections", text: "Pinned and Recent" },
          { type: "p", text: "Each section shows a few forms and **Show N more** to see others. Press the section name to fold it. A folded section moves to the bottom of the sidebar as **Recent (12)**. Press it to open it again." },
          { type: "heading", id: "hide", text: "Hide and resize" },
          {
            type: "list",
            items: [
              "Press the panel icon at the top of the sidebar, or Ctrl+B (⌘+B), to hide it. Press the panel icon that appears in the top bar to bring it back.",
              "Drag the edge of the sidebar to make it wider or narrower. Double-click the edge to reset the width. With the edge focused, the left and right arrow keys resize it.",
            ],
          },
          { type: "p", text: "Both choices are remembered. On a phone the sidebar is always a menu." },
        ],
      },
      {
        slug: "archive",
        title: "Archive and delete",
        summary: "Archive first. Delete for good only from the Archive.",
        blocks: [
          { type: "p", text: "A form cannot be deleted straight from the Library. You archive it first. This stops a slip from losing responses." },
          { type: "heading", id: "archive", text: "Archive a form" },
          { type: "steps", items: ["In the Library, press **…** on the form, then **Archive**. You can also press **Archive** under **More settings** in the builder.", "The form leaves the Library and closes to answers. Its responses are kept.", "A message offers **Undo** for a few seconds."] },
          { type: "heading", id: "restore", text: "Restore" },
          { type: "p", text: "Open **Archive** in the sidebar. Press **Restore** on the form. It returns to your Library, closed if it was published before and as a draft if not." },
          { type: "heading", id: "delete", text: "Delete for good" },
          { type: "steps", items: ["Open **Archive**.", "Press **…** on the form, then **Delete forever**.", "Read the count of responses that will go, and confirm."] },
          { type: "p", text: "Responses, uploaded files, versions and history are deleted with it. This cannot be undone." },
          { type: "tip", text: "Sort the Archive by clicking **Name**, **Responses** or **Archived** at the top of a column." },
        ],
      },
      {
        slug: "undo-and-history",
        title: "Undo and redo",
        summary: "Take back changes in the builder and after actions.",
        blocks: [
          { type: "heading", id: "builder", text: "In the builder" },
          { type: "p", text: "Use the **Undo** and **Redo** arrows at the top, or the keys. Typing joins into one step. Adding, moving, deleting and design changes are each their own step." },
          { type: "keys", items: [{ keys: ["Ctrl", "Z"], label: "Undo" }, { keys: ["Ctrl", "Y"], label: "Redo" }, { keys: ["Ctrl", "Shift", "Z"], label: "Redo" }] },
          { type: "p", text: "The keys do not act while you are typing in a box, so the box's own undo works." },
          { type: "heading", id: "toasts", text: "After an action" },
          { type: "p", text: "Archiving, restoring, saving settings, changing status, changing a custom link and applying a saved theme show a message with **Undo**. It stays for about seven seconds." },
          { type: "heading", id: "recovery", text: "If the page closes" },
          { type: "p", text: "If edits could not be saved, Chaos keeps them on your device. When you come back, press **Restore them**, or **Discard**." },
          { type: "heading", id: "conflict", text: "If someone else edits" },
          { type: "p", text: "If a collaborator changed the form, you can **Load their version** or **Keep mine (overwrite)**. Your edits stay on screen until you choose." },
          { type: "heading", id: "history", text: "Published versions" },
          { type: "p", text: "Older published versions are in **More**, **History**. See [Publish a form](/docs/publish)." },
        ],
      },
      {
        slug: "templates-and-import",
        title: "Templates and import",
        summary: "Start from something instead of a blank page.",
        blocks: [
          { type: "p", text: "Everything you start this way opens as a **draft**. Review it, change anything, then publish." },
          { type: "heading", id: "templates", text: "Start from a template" },
          { type: "steps", items: ["In the Library, press the arrow beside **New**, then **From a template**.", "Choose one. Yours are listed too, with **Use** and a bin to delete."] },
          { type: "heading", id: "built-in", text: "Built-in templates" },
          { type: "p", text: "Chaos includes 21 templates. Each has English and Arabic text, and most use the Google Forms style theme:" },
          { type: "list", items: [
            "**Feedback:** Event or service feedback, Customer satisfaction (CSAT and NPS), Workshop feedback.",
            "**Events and registration:** Event RSVP, Event registration, Volunteer sign-up.",
            "**Customers and orders:** Contact form, Customer intake, Order form, Product feature request, Bug report.",
            "**Work:** Job application, Job or programme application, Employee pulse survey, Team retrospective.",
            "**Education:** Course evaluation, Parent–teacher conference booking, Research survey.",
            "**Quizzes and scoring:** General knowledge quiz and Vocabulary quiz, each with ten questions and an answer key worth one point each, and the scored Self-assessment.",
          ] },
          { type: "tip", text: "Change the placeholder wording, dates and time slots before you publish. Templates only give you the structure." },
          { type: "heading", id: "save-template", text: "Save your own template" },
          { type: "p", text: "In the builder, open **Share**. Under **Export & reuse**, name it in **Save as template** and press the button next to it." },
          { type: "heading", id: "import", text: "Import" },
          { type: "p", text: "Press the arrow beside **New**, then **Import**. You can choose a file (up to 2 MB) or paste text. Chaos reads:" },
          {
            type: "list",
            items: [
              "A Chaos form file.",
              "A Typeform form definition (JSON from the Typeform API).",
              "A Google Forms API export.",
              "Pasted questions, one per paragraph. Start options with \"-\" (or \"[ ]\" for checkboxes). Add \"*\" after a required question. A line starting with \"#\" is the title.",
            ],
          },
          { type: "p", text: "Press **Preview** to see what was found and any warnings before you create the draft." },
        ],
      },
    ],
  },
  {
    id: "settings",
    title: "Settings",
    articles: [
      {
        slug: "app-settings",
        title: "App Settings",
        summary: "One page. Each change applies straight away.",
        blocks: [
          { type: "p", text: "Open [Settings](/dashboard/settings) from the sidebar. Rows show the name on one side and the control on the other. A row in grey is still at its default." },
          { type: "heading", id: "account", text: "Account" },
          { type: "p", text: "**Manage account** opens your profile. **Username** is the first part of your custom links. **Password and security** opens sign-in methods and devices." },
          { type: "heading", id: "appearance", text: "Appearance" },
          {
            type: "list",
            items: [
              "**Appearance**: **Light**, **Dark** or **Auto**, which follows your device.",
              "**Glass**: how see-through menus and popups are, from see-through to 100% solid. **Reset** returns it to the default of 85%.",
              "**Reduce motion**: fewer animations in the workspace.",
            ],
          },
          { type: "p", text: "This is how Chaos looks for you. Forms keep their own look for the people answering." },
          { type: "heading", id: "new-forms", text: "New forms" },
          { type: "p", text: "What a blank form starts with: **Theme**, **Layout** (the mode), **Language** and **Sounds**. Templates and imports keep their own look." },
          { type: "heading", id: "library", text: "Library" },
          { type: "p", text: "**View** (gallery or list) and **Sort by**. There are shortcuts to the **Archive** and **Connections** pages." },
          { type: "heading", id: "shortcuts", text: "Keyboard shortcuts" },
          { type: "p", text: "A list of the main shortcuts. See [Keyboard shortcuts](/docs/keyboard-shortcuts)." },
          { type: "heading", id: "old-quiz", text: "Old quiz editor" },
          { type: "p", text: "Only shown if you still have quizzes made in the old editor. It sets timers, points and shuffling for those." },
          { type: "heading", id: "help", text: "Help" },
          { type: "p", text: "Email for help, the privacy policy, the terms, and **Sign out**." },
        ],
      },
    ],
  },
  {
    id: "connections",
    title: "Connections",
    articles: [
      {
        slug: "connections",
        title: "Connect Max or another app",
        summary: "Let an app create drafts here and read simple counts, with limits you set.",
        blocks: [
          { type: "p", text: "A connection lets another app, such as Max, work with Chaos for you. It cannot publish anything, delete anything, or read what people answered." },
          { type: "heading", id: "what", text: "What a connected app can do" },
          {
            type: "list",
            items: [
              "It reaches only the items you pick, or all your forms and quizzes if you choose that, plus the drafts it makes itself.",
              "It creates and updates **drafts**. You review and publish in Chaos.",
              "It can read summaries that are counts only. They stay hidden until at least 5 people have responded. An option chosen by fewer than 5 people is shown only as **Other**, together with one more option when needed, so nobody can work out the small number. Answers, names, emails and files never leave Chaos.",
              "Unlinking in the other app deletes nothing here.",
              "With **Receive updates (webhooks)** it can ask Chaos to tell it about changes. This is optional; see [Webhooks](/docs/webhooks). If you take this permission away, the app's webhooks stop at once.",
            ],
          },
          { type: "heading", id: "create", text: "Create a connection" },
          {
            type: "steps",
            items: [
              "Open **Connections** in the sidebar and press **New connection**.",
              "Give it a name, for example Max.",
              "Choose permissions: **See titles and status**, **See privacy-safe summaries**, **Create drafts**, **Update drafts**, **Copy questions**.",
              "Choose **Only items I choose**, or **All my forms and quizzes, including future ones**. If you choose items, tick them.",
              "Optionally enter **Expires after (days)**.",
              "Press **Create connection**.",
              "Copy the token shown and paste it into the other app's connection settings. Chaos shows it once and cannot show it again.",
            ],
          },
          { type: "p", text: "The page also shows the **API address** the other app needs." },
          { type: "heading", id: "manage", text: "Manage and revoke" },
          { type: "p", text: "Each connection shows its permissions, when it was made and when it was last used. **Recent activity** lists what it did lately, such as drafts it created or updated. **Change shared items** edits its list. A form's **Share** tab links here." },
          { type: "p", text: "**New token** replaces the token, for example when it may have leaked. Copy the new token into the other app. The old token keeps working for 24 hours so the app does not break; **Stop old token now** ends it early." },
          { type: "p", text: "**Revoke** cuts access at once: the app can no longer read items, create or update drafts, read summaries or receive webhooks. Drafts and items it created stay in Chaos." },
          { type: "p", text: "A connection reaches only items you own. Forms and quizzes that others share with you are not included; their owner has to connect them." },
          { type: "tip", text: "Drafts that an app creates are marked in the builder as created from a connected app. When the app sends details about where the content came from, such as a page link, the builder shows them too. People who answer never see them." },
          { type: "p", text: "Developers: see [Integration API](/docs/integration-api)." },
        ],
      },
      {
        slug: "webhooks",
        title: "Webhooks",
        summary: "Let Chaos tell your own server when a response arrives or a form opens or closes.",
        blocks: [
          { type: "p", text: "A webhook is an address on your server that Chaos calls when something happens. They are optional. Chaos and connected apps work fully without them." },
          { type: "heading", id: "events", text: "What Chaos can tell you" },
          {
            type: "list",
            items: [
              "**Response submitted**: someone finished a form or a quiz.",
              "**Response graded**: you changed the marks of a quiz answer.",
              "**Published**, **Closed** and **Reopened**: a form or quiz changed state.",
            ],
          },
          { type: "heading", id: "create", text: "Add a webhook" },
          {
            type: "steps",
            items: [
              "Open **Connections** in the sidebar. **Webhooks** is below your connections.",
              "Press **New webhook** and enter your server's address. It must start with `https://`.",
              "Tick the events you want.",
              "Choose **All my forms and quizzes** or **Only the ones I choose**.",
              "Press **Create webhook**, then copy the signing secret into your server's settings. Chaos shows it once.",
              "Press **Send test** to check that your server receives it and accepts the signature.",
            ],
          },
          { type: "heading", id: "privacy", text: "What is sent" },
          { type: "p", text: "By default Chaos sends ids, counts, scores and times, never what people answered. Tick **Include answers and respondent names** only if your server may keep personal data. Webhooks made by a connected app never include answers." },
          { type: "heading", id: "security", text: "Signatures and secrets" },
          { type: "p", text: "Every delivery is signed with the webhook's secret, so your server can check it came from Chaos and is recent. **New secret** makes a new one. The old secret keeps working for 24 hours so you can switch without missing anything." },
          { type: "p", text: "Chaos only calls public addresses. Addresses inside a private network are refused." },
          { type: "heading", id: "history", text: "History and failures" },
          {
            type: "list",
            items: [
              "**Delivery history** lists recent deliveries with their result. Press **Resend** to send one again.",
              "If your server does not answer, Chaos tries again for about 15 hours, waiting longer each time.",
              "After 25 failures in a row the webhook is switched off and you get a notification. Fix your server, then press **Resume**.",
              "**Pause** stops deliveries until you resume. **Delete** removes the webhook and its history.",
            ],
          },
          { type: "tip", text: "History is kept for 30 days. The content of a delivery is erased after 7 days, or after 24 hours if it contains answers." },
          { type: "p", text: "Developers: the payload format and how to check a signature are in the [webhook document, version 1](https://github.com/omar-Suleiman14/chaos/blob/main/docs/webhooks-v1.md)." },
        ],
      },
      {
        slug: "integration-api",
        title: "Integration API",
        summary: "For developers: what your code can do with a connection token, and where the full contract is.",
        blocks: [
          { type: "p", text: "The integration API lets your own code, or another app such as Max, work with Chaos through a [connection](/docs/connections). Each connection has its own token, permissions and list of items." },
          { type: "heading", id: "can", text: "What it can do" },
          {
            type: "list",
            items: [
              "List the forms and quizzes the connection can reach, with their titles and status, and read their questions.",
              "Create drafts and update drafts. You review and publish them in Chaos.",
              "Read privacy-safe summaries: counts only, hidden until at least 5 people have responded.",
              "Create and manage its own [webhooks](/docs/webhooks), which never include answers.",
            ],
          },
          { type: "heading", id: "cannot", text: "What it cannot do" },
          {
            type: "list",
            items: [
              "Publish, close or delete anything.",
              "Read individual responses, answer text, names, emails or files.",
              "Add file upload questions, logic, translations or endings. Updating a draft keeps the ones it already has.",
            ],
          },
          { type: "heading", id: "call", text: "Calling the API" },
          {
            type: "list",
            items: [
              "Create a connection under **Connections** and copy its token. The page shows the **API address** to call.",
              "Send the token as `Authorization: Bearer <token>` on every request. Bodies are JSON.",
              "Requests that change something need an `Idempotency-Key` header, so a retry never creates a second draft.",
              "Each connection has a request limit per minute. The response headers say how much is left.",
            ],
          },
          { type: "p", text: "The full contract, with every endpoint, error code and versioning rule, is in the [integration API document, version 1](https://github.com/omar-Suleiman14/chaos/blob/main/docs/integration-api-v1.md)." },
          { type: "tip", text: "To use Chaos from ChatGPT instead of code, see [The Chaos app in ChatGPT](/docs/chatgpt-app)." },
        ],
      },
    ],
  },
  {
    id: "chatgpt",
    title: "ChatGPT",
    articles: [
      {
        slug: "chatgpt-app",
        title: "The Chaos app in ChatGPT",
        summary: "Make and manage forms by talking to ChatGPT. Free on every plan.",
        blocks: [
          { type: "p", text: "With the Chaos app, ChatGPT can work in your Chaos account. It is included on every plan, including free Personal accounts." },
          { type: "heading", id: "connect", text: "Connect it" },
          { type: "p", text: "Chaos is not in the ChatGPT app directory yet. Until it is, add it yourself as a custom app. This takes about two minutes on ChatGPT's web version with a paid plan. In Business and Enterprise workspaces, an admin has to allow developer mode first." },
          {
            type: "steps",
            items: [
              "In ChatGPT on the web, open **Settings → Apps → Advanced settings** and turn on **Developer mode**.",
              "Go back to **Settings → Apps** and choose **Create app**.",
              "Name: **Chaos**. Description: **Create and manage forms, quizzes and games in Chaos**.",
              "MCP server URL: **https://chaos.fail/mcp**.",
              "Authentication: **OAuth**. Leave the client ID and secret empty.",
              "Tick **I trust this application**, then choose **Create**.",
              "Sign in with your Chaos account and approve access. If you are new, an account is created.",
              "In a new chat, choose **+ → Developer mode → Chaos**, or just mention Chaos in your message.",
            ],
          },
          { type: "p", text: "ChatGPT asks before it changes anything. If Chaos gets new abilities later, open the app in **Settings → Apps** and choose **Refresh**." },
          { type: "heading", id: "can", text: "What it can do" },
          {
            type: "list",
            items: [
              "Find your forms and quizzes.",
              "Create a form, survey or quiz as a **draft**, with all its questions. For a quiz, it sets correct answers, points and explanations.",
              "Edit a draft: title, introduction, quiz mode, layout and the question list.",
              "Change a form's theme and sounds.",
              "Publish, when you ask, and give you the link.",
              "Close, reopen, archive and restore a form.",
              "Make a live game draft, open a room for a published quiz, and move the game forward when you ask.",
              "Summarize results, and read individual responses only when you ask.",
            ],
          },
          { type: "heading", id: "cannot", text: "What it cannot do" },
          { type: "list", items: ["It cannot delete anything. Deleting is only in the Archive, in Chaos.", "It cannot change the live version without publishing.", "Classic quizzes from the old editor are read-only.", "File upload questions and custom endings cannot be created from ChatGPT. They are kept when you edit."] },
          { type: "heading", id: "drafts", text: "Drafts first" },
          { type: "p", text: "Everything it creates starts as a draft in your Library. Nothing is shared until you ask it to publish. Open the draft in Chaos to check it." },
          { type: "heading", id: "try", text: "Things to try" },
          {
            type: "list",
            items: [
              "\"Make a 10-question quiz about what we just discussed, using Chaos.\"",
              "\"Create a Chaos feedback form for tonight's workshop with a 1 to 5 rating and one open question.\"",
              "\"How is my Chaos form Team lunch doing?\"",
              "\"Change the theme of my Team lunch form to Midnight and turn sounds off.\"",
              "\"Close my Chaos quiz Chapter 3 review.\"",
            ],
          },
          { type: "heading", id: "privacy", text: "Privacy" },
          { type: "p", text: "What ChatGPT reads is sent to OpenAI. Ask it to read individual answers only when you are allowed to share them. To disconnect, remove Chaos from your apps in ChatGPT's settings. More on [the ChatGPT page](/chatgpt)." },
        ],
      },
    ],
  },
  {
    id: "shortcuts",
    title: "Keyboard shortcuts",
    articles: [
      {
        slug: "keyboard-shortcuts",
        title: "Keyboard shortcuts",
        summary: "Everything you can do without the mouse.",
        blocks: [
          { type: "p", text: "On a Mac, use ⌘ where it says Ctrl." },
          { type: "heading", id: "workspace", text: "In the workspace" },
          {
            type: "keys",
            items: [
              { keys: ["Ctrl", "K"], label: "Search and commands" },
              { keys: ["Ctrl", "B"], label: "Hide or show the sidebar" },
              { keys: ["Esc"], label: "Close a menu, popup or search" },
              { keys: ["↑", "↓"], label: "Move through search results" },
              { keys: ["Enter"], label: "Open the chosen result" },
            ],
          },
          { type: "heading", id: "builder", text: "In the builder" },
          {
            type: "keys",
            items: [
              { keys: ["Ctrl", "Z"], label: "Undo" },
              { keys: ["Ctrl", "Y"], label: "Redo" },
              { keys: ["Ctrl", "Shift", "Z"], label: "Redo" },
            ],
          },
          { type: "heading", id: "answering", text: "When answering a form" },
          { type: "p", text: "These work in the one-at-a-time and swipe modes." },
          {
            type: "keys",
            items: [
              { keys: ["Enter"], label: "Next question" },
              { keys: ["Ctrl", "Enter"], label: "Continue from a long answer, or submit" },
              { keys: ["A", "Z"], label: "Choose an option by its letter" },
              { keys: ["0", "9"], label: "Choose a rating or scale value" },
              { keys: ["↑", "↓"], label: "Previous or next question in swipe mode" },
            ],
          },
          { type: "heading", id: "docs", text: "In these docs" },
          {
            type: "keys",
            items: [
              { keys: ["Ctrl", "K"], label: "Search the docs" },
              { keys: ["/"], label: "Search the docs" },
            ],
          },
        ],
      },
    ],
  },
  {
    id: "languages",
    title: "Languages",
    articles: [
      {
        slug: "languages",
        title: "English and Arabic",
        summary: "Forms in two languages, and Chaos itself in Arabic.",
        blocks: [
          { type: "heading", id: "forms", text: "Forms in English and Arabic" },
          { type: "p", text: "Each form has a main language and can offer another. People can switch at any time. Their answers are the same in both languages because options keep the same identity." },
          {
            type: "steps",
            items: [
              "In the builder, open **More**, then **Translate**.",
              "Tick the languages you want. The main language cannot be unticked.",
              "Under the other language, type a translation next to each original: the title, introduction, each question, description, option, row, label and ending.",
            ],
          },
          { type: "p", text: "The count next to each language shows how many items are missing, or **Complete**. Anything not translated shows in the main language." },
          { type: "tip", text: "Changing the main language does not translate existing text. Move text between languages yourself." },
          { type: "heading", id: "respondents", text: "What respondents see" },
          { type: "p", text: "A form opens in the language in the link if you added `?lang=ar` or `?lang=en`. If not, it uses the person's browser language when the form has it, and the main language if not. Arabic forms read right to left." },
          { type: "heading", id: "new-default", text: "The default for new forms" },
          { type: "p", text: "Choose **English** or **العربية** under **New forms** in [Settings](/dashboard/settings)." },
          { type: "heading", id: "app", text: "Chaos in Arabic" },
          { type: "p", text: "The website and these docs are available in Arabic. Use the language button in the header of the website, or the button in the top bar of these docs. The choice is remembered on your device, and the page switches to right to left." },
          { type: "p", text: "Results show which language each response used." },
        ],
      },
    ],
  },
  {
    id: "account-plans",
    title: "Account and plans",
    articles: [
      {
        slug: "account",
        title: "Sign in and sign out",
        summary: "Your account, your username, and leaving safely.",
        blocks: [
          { type: "heading", id: "sign-in", text: "Sign in" },
          { type: "p", text: "Open Chaos and press the sign-in button. Chaos uses Clerk for sign-in. The first time you sign in, your account and a library are created." },
          { type: "heading", id: "sign-out", text: "Sign out" },
          {
            type: "list",
            items: [
              "**On a computer**: press your picture at the bottom of the sidebar, then **Sign out**.",
              "**On a phone**: open the menu, then press **Sign out** at the bottom. It shows your name.",
              "**From Settings**: open [Settings](/dashboard/settings), go to **Help**, and press **Sign out**.",
            ],
          },
          { type: "heading", id: "manage", text: "Manage your account" },
          { type: "p", text: "In [Settings](/dashboard/settings), **Manage account** and **Password and security** open your profile, sign-in methods and devices." },
          { type: "heading", id: "username", text: "Your username" },
          { type: "p", text: "It is the first part of custom links, such as `chaos.fail/yourname/my-form`. Choose one in Settings. Some words are reserved and cannot be used." },
        ],
      },
      {
        slug: "plans",
        title: "Plans",
        summary: "Personal is free; Business pays per seat.",
        blocks: [
          { type: "p", text: "Personal use is free, with every feature and no monthly caps. Business is planned at 50 EGP per active creator seat per month; respondents, students and Live players never need seats. Checkout is not live and nobody is automatically charged. Every account allows up to 10 MiB per form upload and 25 MiB per teaching source file; these are not total storage allowances. See [Pricing](/pricing)." },
          { type: "heading", id: "free", text: "Personal" },
          { type: "p", text: "Unlimited forms, surveys, quizzes and responses, Live games with up to 500 players, the Chaos app in ChatGPT and branding removal. Rate limits and security checks still apply." },
          { type: "heading", id: "pro", text: "Business" },
          { type: "list", items: ["The same product, licensed for business use.", "50 EGP per active creator seat per month: only people who create or manage content."] },
          { type: "p", text: "Businesses can request seats through Support until checkout is available." },
          { type: "tip", text: "Questions about a plan? See [Support](/support)." },
        ],
      },
      {
        slug: "get-help",
        title: "Get help",
        summary: "Where to ask a question, report a problem or check the service.",
        blocks: [
          { type: "p", text: "The [Support](/support) page has the contact email, the status page when there is one, and these links." },
          {
            type: "list",
            items: [
              "**Questions about your account or a form**: email support from the [Support](/support) page. Say which form, with its link, and what you expected.",
              "**Bugs and feature ideas**: open an issue on [GitHub](https://github.com/omar-Suleiman14/chaos/issues). Do not include respondent data.",
              "**Security problems**: report them privately, never in a public issue. See [Support](/support#security).",
            ],
          },
          { type: "tip", text: "If Chaos shows a **Reference** code on an error screen, include it. It helps find what went wrong." },
        ],
      },
    ],
  },
  {
    id: "open-source",
    title: "Open source",
    articles: [
      {
        slug: "self-hosting",
        title: "Open source and self-hosting",
        summary: "Chaos is open source under the AGPL. Run your own copy with Docker.",
        blocks: [
          { type: "p", text: "The source code of Chaos is public on [GitHub](https://github.com/omar-Suleiman14/chaos) under the GNU AGPL, version 3 or later. You can read it, report issues, suggest changes and run your own copy." },
          { type: "heading", id: "need", text: "What you need" },
          {
            type: "list",
            items: [
              "Docker with Compose. The setup runs the Chaos app and a self-hosted Convex backend.",
              "A Clerk account for sign-in. Clerk is a hosted service, and Chaos cannot run without it today.",
              "A domain with HTTPS for anything beyond a trial on your own computer.",
            ],
          },
          { type: "heading", id: "start", text: "Get started" },
          { type: "p", text: "Follow the [self-hosting guide](https://github.com/omar-Suleiman14/chaos/blob/main/docs/self-hosting.md). It covers environment variables, Clerk, a reverse proxy, backups and upgrades." },
          { type: "heading", id: "status", text: "Current status" },
          { type: "p", text: "The Docker setup has not been tested end to end yet. Treat it as a starting point, and report rough edges on [GitHub issues](https://github.com/omar-Suleiman14/chaos/issues)." },
          { type: "heading", id: "differences", text: "How it differs from chaos.fail" },
          {
            type: "list",
            items: [
              "You run backups, monitoring and updates yourself.",
              "Set `NEXT_PUBLIC_APP_URL` and `CHAOS_APP_URL` to your own address, or links point at chaos.fail.",
              "The integration API and webhooks need the backend's HTTP port to be reachable.",
              "Analytics is off unless you set it up.",
            ],
          },
          { type: "heading", id: "license", text: "The license" },
          { type: "p", text: "The AGPL lets you use, change and share Chaos. If you change it and let people use your version over a network, you must offer them its source code. The [LICENSE](https://github.com/omar-Suleiman14/chaos/blob/main/LICENSE) file has the exact terms." },
        ],
      },
    ],
  },
];
